<?php
/**
 * algorithm_coverage_php.php — completeness cross-check for the algorithm set.
 *
 * Nothing else binds the places an algorithm name must appear together: the
 * shared fixture (generated by the Python source of truth), the PHP engine
 * (CheckCharacter::compute / checkAlphabet / nCheckChars), the server allow-list
 * (AnnotationRules::ALGORITHMS), and the end-user dropdown (config.json). The
 * parity tests only prove that fixture rows recompute; they do NOT catch an
 * algorithm registered in one place and missing from another (a scheme added to
 * the engine but not the allow-list would ship as "unconfigurable"; one added to
 * the dropdown but not the engine would throw at runtime). This test asserts the
 * sets are identical, so a half-wired algorithm fails CI instead of shipping.
 *
 * Run:  php tests/algorithm_coverage_php.php
 */

require_once __DIR__ . '/../php/CheckCharacter.php';
require_once __DIR__ . '/../php/AnnotationRules.php';

use INSPIRE\UniversalValidator\CheckCharacter;
use INSPIRE\UniversalValidator\AnnotationRules;

$n = 0;
$fail = 0;

function check($label, $cond)
{
    global $n, $fail;
    $n++;
    if (!$cond) {
        $fail++;
        fwrite(STDERR, "FAIL: $label\n");
    }
}

// ---- the source-of-truth set: the fixture's algorithm metadata ----
$fx = json_decode(file_get_contents(__DIR__ . '/check_fixture.json'), true);
$fixtureAlgos = [];
$fixtureMeta = [];
foreach ($fx['algorithms'] as $a) {
    $fixtureAlgos[] = $a['name'];
    $fixtureMeta[$a['name']] = $a;
}
sort($fixtureAlgos);

// ---- config.json end-user dropdown ----
$cfg = json_decode(file_get_contents(__DIR__ . '/../config.json'), true);
$dropdown = [];
foreach ($cfg['project-settings'] as $s) {
    if (($s['key'] ?? '') !== 'rules') continue;
    foreach ($s['sub_settings'] as $sub) {
        if (($sub['key'] ?? '') !== 'algorithm') continue;
        foreach ($sub['choices'] as $c) $dropdown[] = $c['value'];
    }
}
sort($dropdown);

// ---- server allow-list ----
$allow = AnnotationRules::ALGORITHMS;
sort($allow);

// ---- set equality across every surface (all anchored to the fixture) ----
check('fixture set == server allow-list (AnnotationRules::ALGORITHMS)', $fixtureAlgos === $allow);
check('fixture set == config.json algorithm dropdown', $fixtureAlgos === $dropdown);

// ---- the PHP engine supports every fixture algorithm coherently ----
foreach ($fixtureAlgos as $name) {
    $meta = $fixtureMeta[$name];
    check("nCheckChars matches fixture for $name",
        CheckCharacter::nCheckChars($name) === (int) $meta['n_check_chars']);
    if ($name === 'none') {
        check('checkAlphabet empty for none', CheckCharacter::checkAlphabet($name) === '');
        continue;
    }
    check("checkAlphabet matches fixture for $name",
        CheckCharacter::checkAlphabet($name) === $meta['check_alphabet']);
    // compute() must accept the name (never fall through to "unknown algorithm")
    // and agree with the fixture on a real payload.
    $row = null;
    foreach ($fx['compute'] as $r) {
        if ($r['name'] === $name) { $row = $r; break; }
    }
    check("compute() supports $name and matches the fixture",
        $row !== null && CheckCharacter::compute($name, $row['payload']) === $row['check']);
}

// ---- every shorthand resolves to a canonical name that is in the set ----
foreach (AnnotationRules::ALGORITHM_SYNONYMS as $canon => $syns) {
    check("synonym target '$canon' is a real algorithm", in_array($canon, $fixtureAlgos, true));
    foreach ($syns as $s) {
        check("shorthand '$s' canonicalizes to '$canon'",
            AnnotationRules::canonicalAlgorithm($s) === $canon);
    }
}

echo sprintf("algorithm_coverage_php: %d checks, %d failure(s)\n", $n, $fail);
exit($fail === 0 ? 0 : 1);
