<?php
/**
 * scan_identity_php.php — WHICH RULE a durable finding is filed against.
 *
 * This suite exists because of a specific hole. Nothing in tests/ has ever
 * referenced durableScanContext() or durableEvaluateRecord(), and that is the
 * seam where the rule engine's output becomes database rows: where the host
 * form, the value preview, the uniqueness candidate key and — the subject here
 * — the rule identity are decided. Every live pilot of the durable scan died at
 * that seam, and the 22 mocked suites plus 286 real-database checks stayed green
 * through all of them.
 *
 * What it locks:
 *
 *   I-01  DROPPING A RULE DOES NOT RENAME THE OTHERS. scanPlan() builds
 *         $plan['live'] with PRESERVED keys — it skips config-broken rules, and
 *         the per-instrument-rights gate unsets more — so the array is SPARSE
 *         and its keys are rule ordinals. identifyAll() re-indexed it densely
 *         and durableEvaluateRecord() then looked the identity up by ordinal-1,
 *         so one dropped rule shifted every later rule's name by one and pushed
 *         the last one off the end into the `unnamed:` fallback.
 *
 *         That is not a labelling bug. rule_source_id is hashed into
 *         Hmac::findingIdentity(), so a mis-attributed finding gets the IDENTITY
 *         of a rule that did not produce it — and identity is the key the
 *         incremental supersede logic matches on.
 *
 *         The check is written as a comparison rather than against a fixture,
 *         because a fixture would have to be generated by the code under test:
 *         scan the same project twice, once with a rule barred and once with it
 *         visible, and require that the rules present in BOTH runs keep the same
 *         name. That property is what a stored finding depends on and it cannot
 *         be satisfied by a dense re-index.
 *
 *   I-02  A SETTINGS RULE IS NAMED AS ONE. Origin used to be inferred from a
 *         positional `settingsCount` that no production caller ever supplied, so
 *         every settings rule was named through the annotation branch. The two
 *         branches share one namespace that the `set:` / `ann:` prefixes exist to
 *         keep apart, and the annotation branch names a rule by its FIELD LIST —
 *         so a settings rule and an annotation rule of the same family on the
 *         same field produced the same stem and were separated only by a counter
 *         assigned in list order. Deleting one renamed the other.
 *
 *         The count could not have been made correct either: Branching::resolve()
 *         drops rules that lost every field to a branch rule and appends
 *         synthesized ones, so no integer boundary survives it. Origin therefore
 *         travels ON the rule.
 *
 *   I-03  THE FINGERPRINT COVERS THE RULE SET, NOT ITS ORDER. It folded a
 *         positional ordinal in, so reordering rules — nothing added, removed or
 *         edited — made fingerprintMatches() report that the configuration had
 *         moved underneath the run. Annotation rule order follows data-dictionary
 *         field order, so moving a field in the Online Designer invalidated every
 *         resumable run on the project. identify()'s own docblock says moving a
 *         field must not rename the rule written on it; the run-level guard was
 *         contradicting the identity layer.
 *
 *   I-04  identifyAll() ANSWERS WITH THE KEYS IT WAS ASKED WITH. The unit-level
 *         statement of I-01, so a future dense re-index fails here first, with a
 *         one-line diagnosis, rather than three layers up as a wrong rule name.
 *
 * Every check below fails on the pre-fix tree. Run:  php tests/scan_identity_php.php
 */

namespace ExternalModules {
    class AbstractExternalModule {
        public $logCalls = []; public $subSettings = []; public $projectSettings = [];
        public $systemSettings = []; public $projectIdReturn = null;
        public function getSubSettings($k, $pid = null) {
            $e = ($pid !== null && $pid !== '') ? $pid : $this->projectIdReturn;
            return $e ? $this->subSettings : [];
        }
        public function getProjectSetting($k, $pid = null) {
            $e = ($pid !== null && $pid !== '') ? $pid : $this->projectIdReturn;
            if (!$e) return null;
            return isset($this->projectSettings[$k]) ? $this->projectSettings[$k] : null;
        }
        public function getSystemSetting($k) {
            return isset($this->systemSettings[$k]) ? $this->systemSettings[$k] : null;
        }
        public function setSystemSetting($k, $v) { $this->systemSettings[$k] = $v; }
        /**
         * A repeatable sub-setting is stored as ONE parallel array per sub-key,
         * indexed by row. Modelled faithfully because the minting writes the
         * whole column at once, and a mock that accepted a partial write would
         * bless exactly the bug the whole-column write exists to avoid.
         */
        public function setProjectSetting($k, $v, $pid = null) {
            $this->projectSettings[$k] = $v;
            if (is_array($v)) {
                foreach ($v as $i => $one) {
                    if (isset($this->subSettings[$i])) $this->subSettings[$i][$k] = $one;
                }
            }
        }
        public function query($sql, $params = []) { return []; }
        public function getProjectId() { return $this->projectIdReturn; }
        public function getUrl($p) { return '/x/' . $p; }
        public function log($m, $p = []) { $this->logCalls[] = [$m, $p]; return count($this->logCalls); }
        public function initializeJavascriptModuleObject() { return '<script></script>'; }
        public function getJavascriptModuleObjectName() { return 'EM.T.UV'; }
        public function getUser() { return new TestUser('nurse'); }
    }
    class TestUser {
        /** Per-instrument rights. Barring one form is how a middle rule is dropped. */
        public static $forms = ['fa' => '1', 'fb' => '1', 'fc' => '1', 'fr' => '1'];
        private $n; public function __construct($n) { $this->n = $n; }
        public function getUsername() { return $this->n; }
        public function hasDesignRights() { return true; }
        public function getRights($pid = null) {
            return self::$forms === null ? [] : ['forms' => self::$forms];
        }
    }
}

namespace {
    class REDCap {
        public static $data = []; public static $dictionary = [];
        public static function getDataDictionary($pid, $f = 'array') { return self::$dictionary; }
        public static function getData($p) {
            $src = self::$data;
            if (!empty($p['records'])) {
                $only = [];
                foreach ($p['records'] as $r) {
                    if (array_key_exists($r, self::$data)) $only[$r] = self::$data[$r];
                }
                $src = $only;
            }
            return $src;
        }
        public static function getRecordIdField() { return 'record_id'; }
    }
}

namespace {
    require_once __DIR__ . '/../UniversalValidator.php';

    const PID = 77;
    $n = 0; $fail = 0;
    function check($label, $cond) {
        global $n, $fail; $n++;
        if (!$cond) { $fail++; fwrite(STDERR, "FAIL: $label\n"); }
    }

    /** A dictionary from [field => [form, annotation]]. */
    function dict(array $spec) {
        $d = [];
        foreach ($spec as $f => $s) {
            $d[$f] = ['field_type' => 'text', 'form_name' => $s[0],
                      'field_annotation' => isset($s[1]) ? $s[1] : ''];
        }
        return $d;
    }

    function mkMod($dict, $data, $subs = []) {
        $m = new \INSPIRE\UniversalValidator\UniversalValidator();
        $m->subSettings = $subs;
        $m->projectSettings = ['log-values' => ''];
        $m->projectIdReturn = PID;
        \REDCap::$dictionary = $dict;
        \REDCap::$data = $data;
        return $m;
    }

    /**
     * Scan one record through the REAL seam and answer field => rule_source_id.
     *
     * Deliberately through durableScanContext()'s own evaluate closure rather
     * than by calling durableEvaluateRecord() directly: the closure is what
     * binds the plan, the generation and the identity list together, and binding
     * them is where the defect lived.
     */
    function identitiesByField($m, $recordId) {
        // The generation is REQUIRED now, and null means planning. There is no
        // default: a default is what wrote generation 1 for every run of every
        // project on the installation and wedged every second scan.
        $ctx = $m->durableScanContext(PID, ['valueCeiling' => 'locations',
                                            'generation' => 7, 'runSeq' => 7]);
        if (empty($ctx['ok'])) return ['__why' => $ctx['why']];
        $ev = $ctx['evaluate'];
        $node = \REDCap::$data[$recordId];
        $r = $ev($recordId, $node);
        $out = [];
        foreach ($r['findings'] as $f) {
            $out[$f['field']] = $f['rule_source_id'];
        }
        $out['__ords'] = [];
        foreach ($r['findings'] as $f) $out['__ords'][$f['field']] = $f['rule_ord'];
        $out['__problems'] = isset($r['problems']) ? count($r['problems']) : 0;
        return $out;
    }

    /* =====================================================================
     * I-01  dropping a rule does not rename the others
     * ===================================================================== */
    {
        // Four assert rules, one per form, each naming only its own field so
        // nothing is cross-form and every rule is independently violable. The
        // messages differ so groupMulti cannot pool them into one rule.
        $mk = function ($bAnnotation) {
            return dict([
                'record_id' => ['fa'],
                'a_val' => ['fa', '@UVASSERT={"assert":"[a_val]=\'OK\'","message":"m1","blockSave":"hard"}'],
                'b_val' => ['fb', $bAnnotation],
                'c_val' => ['fc', '@UVASSERT={"assert":"[c_val]=\'OK\'","message":"m3","blockSave":"hard"}'],
                'r_val' => ['fr', '@UVASSERT={"assert":"[r_val]=\'OK\'","message":"m4","blockSave":"hard"}'],
            ]);
        };
        $GOOD_B   = '@UVASSERT={"assert":"[b_val]=\'OK\'","message":"m2","blockSave":"hard"}';
        // Truncated JSON. The most ordinary misconfiguration there is - and
        // scanPlan goes out of its way to REPORT a config-broken rule rather
        // than drop it silently, which is exactly why the gap it leaves in
        // $plan['live'] is routine rather than exotic.
        $BROKEN_B = '@UVASSERT={"assert":';

        // Every value wrong, so every surviving rule produces exactly one finding.
        $data = [1 => [1 => ['record_id' => '1', 'a_val' => 'X', 'b_val' => 'X',
                             'c_val' => 'X', 'r_val' => 'X']]];

        // PASS 1: the rule at ordinal 2 is config-broken, so scanPlan skips it
        // and $plan['live'] becomes {0, 2, 3} - sparse, gap in the middle.
        $barred = identitiesByField(mkMod($mk($BROKEN_B), $data), 1);

        check('I-01: with one rule config-broken, the other three are still examined',
            isset($barred['a_val'], $barred['c_val'], $barred['r_val']));
        check('I-01: and the broken rule contributes no finding',
            !isset($barred['b_val']));
        // The last rule is the one that fell off the end of the dense list.
        check('I-01: no finding is filed under a placeholder rule name',
            isset($barred['r_val']) && strpos($barred['r_val'], 'unnamed:') !== 0
            && isset($barred['c_val']) && strpos($barred['c_val'], 'unnamed:') !== 0);
        check('I-01: and nothing is reported as an internal identity failure',
            isset($barred['__problems']) && $barred['__problems'] === 0);
        // The ordinals themselves are the sparse keys, which is what makes the
        // lookup index meaningful in the first place.
        check('I-01: the ordinals are the true rule positions, not compacted ones',
            isset($barred['__ords']['c_val']) && $barred['__ords']['c_val'] === 3
            && isset($barred['__ords']['r_val']) && $barred['__ords']['r_val'] === 4);

        // PASS 2: the same project, the same record, the same three surviving
        // rules - but b_val's annotation is now well-formed, so nothing is
        // dropped and $plan['live'] is dense.
        $whole = identitiesByField(mkMod($mk($GOOD_B), $data), 1);

        check('I-01: with nothing barred, all four rules are examined',
            isset($whole['a_val'], $whole['b_val'], $whole['c_val'], $whole['r_val']));

        // THE PROPERTY. A rule's name is a property of the rule, not of how many
        // OTHER rules happened to survive the plan. Under the dense re-index,
        // c_val took r_val's name in pass 1 and its own in pass 2, and r_val had
        // no name at all in pass 1 - so a finding stored by one run could never
        // be matched by the next.
        check('I-01: a rule keeps its name when an unrelated rule is dropped (a_val)',
            $barred['a_val'] === $whole['a_val']);
        check('I-01: a rule keeps its name when an EARLIER rule is dropped (c_val)',
            $barred['c_val'] === $whole['c_val']);
        check('I-01: including the last rule in the list (r_val)',
            $barred['r_val'] === $whole['r_val']);

        // And the four names are four names. A collision would make two rules
        // one rule in the store, which the identity key cannot represent.
        $names = [$whole['a_val'], $whole['b_val'], $whole['c_val'], $whole['r_val']];
        check('I-01: four rules produce four distinct identities',
            count(array_unique($names)) === 4);
    }

    /* =====================================================================
     * I-02  a settings rule is named as a settings rule
     * ===================================================================== */
    {
        $D = dict([
            'record_id' => ['fa'],
            's_val'     => ['fa'],
        ]);
        $data = [1 => [1 => ['record_id' => '1', 's_val' => 'X']]];
        // One settings rule, configured the way the settings dialog stores them.
        $subs = [[
            'rule-type'  => 'constraint',
            'fields'     => ['s_val'],
            'assert'     => "[s_val]='OK'",
            'message'    => 'from the dialog',
            'block-save' => 'hard',
        ]];
        \ExternalModules\TestUser::$forms = ['fa' => '1', 'fb' => '1', 'fc' => '1', 'fr' => '1'];
        $m = mkMod($D, $data, $subs);
        $got = identitiesByField($m, 1);

        // If the settings dialog shape above does not produce a rule on this
        // build, the check below would pass vacuously. Assert the premise.
        check('I-02: the settings rule produced a finding (the premise of this block)',
            isset($got['s_val']));
        if (isset($got['s_val'])) {
            check('I-02: a settings rule is named through the settings branch',
                strpos($got['s_val'], 'set:') === 0 || strpos($got['s_val'], 'uid:') === 0);
            check('I-02: and never through the annotation branch, whose namespace it would share',
                strpos($got['s_val'], 'ann:') !== 0);
        }
    }

    /* =====================================================================
     * I-03  the fingerprint covers the rule SET, not its order
     * ===================================================================== */
    {
        $P = '\INSPIRE\UniversalValidator\Scan\ScanPlanner';
        $r1 = ['type' => 'assert', 'fields' => ['f1'], 'assert' => "[f1]='A'", '_origin' => 'annotation'];
        $r2 = ['type' => 'assert', 'fields' => ['f2'], 'assert' => "[f2]='B'", '_origin' => 'annotation'];
        $r3 = ['type' => 'assert', 'fields' => ['f3'], 'assert' => "[f3]='C'", '_origin' => 'annotation'];

        $req = function ($rules) {
            return ['rules' => $rules, 'engine' => '1.0', 'ownership' => [],
                    'structure' => [], 'choices' => [], 'policy' => []];
        };
        // plan() needs a store and a source to run end to end, so reach the
        // fingerprint the way plan() does instead: identify, spec, hash.
        $fpOf = function ($rules) use ($P) {
            $ids = $P::identifyAll($rules);
            $spec = [];
            foreach ($ids as $id) {
                $spec[] = ['id' => $id['source_id'], 'rev' => $id['revision'], 'origin' => $id['origin']];
            }
            usort($spec, function ($a, $b) {
                $c = strcmp($a['id'], $b['id']);
                return $c !== 0 ? $c : strcmp($a['rev'], $b['rev']);
            });
            return $P::fingerprint(['engine' => '1.0', 'rules' => $spec, 'ownership' => [],
                                    'structure' => [], 'choices' => [],
                                    'gapPolicy' => 'separate', 'valueMode' => 'locations']);
        };

        check('I-03: reordering the rule list does not move the fingerprint',
            $fpOf([$r1, $r2, $r3]) === $fpOf([$r3, $r1, $r2]));
        check('I-03: but EDITING a rule does',
            $fpOf([$r1, $r2, $r3])
            !== $fpOf([$r1, $r2, ['type' => 'assert', 'fields' => ['f3'],
                                  'assert' => "[f3]='CHANGED'", '_origin' => 'annotation']]));
        check('I-03: and so does removing one',
            $fpOf([$r1, $r2, $r3]) !== $fpOf([$r1, $r2]));
    }

    /* =====================================================================
     * I-04  identifyAll answers with the keys it was asked with
     * ===================================================================== */
    {
        $P = '\INSPIRE\UniversalValidator\Scan\ScanPlanner';
        $sparse = [
            0 => ['type' => 'assert', 'fields' => ['f1'], 'assert' => "[f1]='A'", '_origin' => 'annotation'],
            2 => ['type' => 'assert', 'fields' => ['f3'], 'assert' => "[f3]='C'", '_origin' => 'annotation'],
            5 => ['type' => 'assert', 'fields' => ['f6'], 'assert' => "[f6]='F'", '_origin' => 'settings'],
        ];
        $ids = $P::identifyAll($sparse);
        check('I-04: the answer carries the caller\'s keys, gaps and all',
            array_keys($ids) === [0, 2, 5]);
        check('I-04: and one entry per rule', count($ids) === 3);
        check('I-04: origin is read from the rule, with no positional count supplied',
            $ids[5]['origin'] === 'settings' && $ids[0]['origin'] === 'annotation');
        check('I-04: a settings rule without a stored uid still gets a settings name',
            strpos($ids[5]['source_id'], 'set:') === 0);

        // The deprecated positional fallback still answers for an untagged list,
        // so an external caller is not broken by the change.
        $untagged = [
            ['type' => 'assert', 'fields' => ['f1'], 'assert' => "[f1]='A'"],
            ['type' => 'assert', 'fields' => ['f2'], 'assert' => "[f2]='B'"],
        ];
        $legacy = $P::identifyAll($untagged, 1);
        check('I-04: the positional fallback still names an untagged list',
            $legacy[0]['origin'] === 'settings' && $legacy[1]['origin'] === 'annotation');

        // Origin must not enter the content hash: it is already in the prefix,
        // and hashing it would churn every stored revision for nothing.
        $bare = ['type' => 'assert', 'fields' => ['f1'], 'assert' => "[f1]='A'"];
        $tagged = $bare; $tagged['_origin'] = 'annotation';
        check('I-04: tagging a rule with its origin does not change its revision',
            $P::revision($bare) === $P::revision($tagged));
    }

    /* =====================================================================
     * I-05  a settings rule keeps its name when the list is reordered
     *
     * identify() has always preferred a persistent id stored on the row, and
     * its comment has always said why: an id "survives editing the rule -
     * which is the one thing a content hash cannot do". Nothing ever minted
     * one, so every project ran the content-hash fallback.
     *
     * That fallback is worse than merely fragile. revision() deliberately
     * discards the field list, so two rules of the same kind and options on
     * DIFFERENT fields hash identically and are separated only by an occurrence
     * counter assigned in list order. Dragging one row above the other swapped
     * their identities, and every finding stored against them was silently
     * re-attributed to the other rule.
     * ===================================================================== */
    {
        $D = dict(['record_id' => ['fa'], 'x_val' => ['fa'], 'y_val' => ['fa']]);
        $data = [1 => [1 => ['record_id' => '1', 'x_val' => '', 'y_val' => '']]];
        // Two rows identical in everything revision() hashes, differing only in
        // the field - which is precisely what revision() throws away.
        $rowX = ['rule-type' => 'required', 'fields' => ['x_val']];
        $rowY = ['rule-type' => 'required', 'fields' => ['y_val']];

        // Before minting: the content-hash fallback, and the swap it permits.
        $before  = identitiesByField(mkMod($D, $data, [$rowX, $rowY]), 1);
        $swapped = identitiesByField(mkMod($D, $data, [$rowY, $rowX]), 1);
        check('I-05: the premise - both rows produce a finding',
            isset($before['x_val'], $before['y_val'], $swapped['x_val'], $swapped['y_val']));
        check('I-05: without an id, reordering the rows renames the rules',
            $before['x_val'] !== $swapped['x_val']);

        // Mint. This is what a settings save now does.
        $m = mkMod($D, $data, [$rowX, $rowY]);
        $m->redcap_module_save_configuration(PID);
        $minted = $m->subSettings;
        check('I-05: every row is given an id',
            isset($minted[0]['rule-uid'], $minted[1]['rule-uid'])
            && preg_match('/^[0-9a-f]{16}\z/', $minted[0]['rule-uid'])
            && preg_match('/^[0-9a-f]{16}\z/', $minted[1]['rule-uid']));
        check('I-05: and the two ids differ',
            $minted[0]['rule-uid'] !== $minted[1]['rule-uid']);

        // An id already present is never reissued: a changed id orphans stored
        // findings, which is strictly worse than never having had one.
        $again = mkMod($D, $data, $minted);
        $again->redcap_module_save_configuration(PID);
        check('I-05: a second save does not reissue an id that already exists',
            $again->subSettings[0]['rule-uid'] === $minted[0]['rule-uid']
            && $again->subSettings[1]['rule-uid'] === $minted[1]['rule-uid']);

        // THE PROPERTY. With ids, the name follows the ROW rather than the
        // position, so dragging rows in the dialog cannot re-attribute a finding.
        $withIds     = identitiesByField(mkMod($D, $data, $minted), 1);
        $withIdsSwap = identitiesByField(mkMod($D, $data, [$minted[1], $minted[0]]), 1);
        check('I-05: an identified rule is named by its id',
            strpos($withIds['x_val'], 'uid:') === 0);
        check('I-05: and reordering the rows no longer renames it',
            $withIds['x_val'] === $withIdsSwap['x_val']
            && $withIds['y_val'] === $withIdsSwap['y_val']);
        check('I-05: while the two rules still have two names',
            $withIds['x_val'] !== $withIds['y_val']);
    }

    /* =====================================================================
     * I-06  two hidden options ticked on one checkbox are TWO findings
     *
     * A @UVCHOICES rule on a CHECKBOX emits one finding per ticked hidden code,
     * all with reason `hidden-choice` and all at the same record, event,
     * instance, form and field, under the same rule. The identity hashed
     * exactly those seven facts, so the two were byte-identical: the unique key
     * refused the second, commitBatch rolled the WHOLE batch back, and a FIRST
     * scan of a fresh project stored nothing at all for records it had examined
     * correctly. No prior scan involved, no second run needed.
     *
     * The fix is a within-location discriminator inside the hash - the ticked
     * choice CODE - and NOT an ordinal. An ordinal renumbers every later
     * finding when an earlier one is fixed, so a re-scan would close and reopen
     * rows that never changed, which destroys the one property the identity
     * exists to provide. The second half of this block is what pins that.
     * ===================================================================== */
    {
        $D = ['record_id' => ['field_type' => 'text', 'form_name' => 'fa', 'field_annotation' => ''],
              'symptoms'  => ['field_type' => 'checkbox', 'form_name' => 'fa',
                              'select_choices_or_calculations' => '1, Cough | 2, Fever | 3, Rash',
                              'field_annotation' => '@UVCHOICES={"hide":["2","3"]}']];
        // BOTH hidden options ticked. REDCap presents a checkbox as a map of
        // code => '1', which is the shape the rule reads.
        $data = [1 => [1 => ['record_id' => '1',
                             'symptoms' => ['1' => '1', '2' => '1', '3' => '1']]]];

        $m = mkMod($D, $data);
        $ctx = $m->durableScanContext(PID, ['valueCeiling' => 'locations',
                                            'generation' => 3, 'runSeq' => 3]);
        check('I-06: the premise - the checkbox rule is scannable',
            !empty($ctx['ok']));
        if (!empty($ctx['ok'])) {
            $ev = $ctx['evaluate'];
            $r  = $ev(1, $data[1]);

            $hidden = [];
            foreach ($r['findings'] as $f) {
                if ($f['reason_code'] === \INSPIRE\UniversalValidator\Scan\ReasonCode::code('hidden-choice')) {
                    $hidden[] = $f;
                }
            }
            check('I-06: both ticked hidden options are reported, not one',
                count($hidden) === 2);
            check('I-06: and they are two DIFFERENT findings, which the unique key can hold',
                count($hidden) === 2
                && $hidden[0]['identity'] !== $hidden[1]['identity']);
            check('I-06: nothing was collapsed to get there',
                isset($r['collapsed']) && $r['collapsed'] === 0);
            // The two are at ONE location by every other measure. If any of
            // these stopped being equal the test would be passing for the wrong
            // reason - two findings that differ in their field are not the case
            // this block is about.
            check('I-06: at the same field, rule and reason - only the option differs',
                count($hidden) === 2
                && $hidden[0]['field'] === $hidden[1]['field']
                && $hidden[0]['rule_source_id'] === $hidden[1]['rule_source_id']
                && $hidden[0]['reason_code'] === $hidden[1]['reason_code']
                && $hidden[0]['host_form'] === $hidden[1]['host_form']);

            // STABILITY, which is the whole reason the discriminator is the
            // choice code rather than a counter. Scan the same record again and
            // the same two identities must come back - otherwise an incremental
            // run closes and reopens rows nothing changed.
            $again = $ev(1, $data[1]);
            $ids1 = []; foreach ($hidden as $f) $ids1[] = bin2hex($f['identity']);
            $ids2 = [];
            foreach ($again['findings'] as $f) {
                if ($f['reason_code'] === \INSPIRE\UniversalValidator\Scan\ReasonCode::code('hidden-choice')) {
                    $ids2[] = bin2hex($f['identity']);
                }
            }
            sort($ids1); sort($ids2);
            check('I-06: and a re-scan produces the same two identities', $ids1 === $ids2);

            // UNTICKING ONE MUST NOT RENAME THE OTHER. This is the property an
            // ordinal discriminator would fail: with a counter, removing the
            // first finding renumbers the second, and every stored row for it
            // is orphaned.
            // THE SAME evaluator, a different reading of the record. A second
            // module would mint a second HMAC key and every identity would
            // differ for a reason that has nothing to do with the rule - which
            // would make this check pass or fail on the fixture rather than on
            // the behaviour.
            $one = [1 => ['record_id' => '1',
                          'symptoms' => ['1' => '1', '2' => '0', '3' => '1']]];
            $r2 = $ev(1, $one);
            $left = [];
            foreach ($r2['findings'] as $f) {
                if ($f['reason_code'] === \INSPIRE\UniversalValidator\Scan\ReasonCode::code('hidden-choice')) {
                    $left[] = bin2hex($f['identity']);
                }
            }
            check('I-06: unticking one hidden option leaves exactly the other',
                count($left) === 1);
            check('I-06: and does NOT rename it, which an ordinal would have',
                count($left) === 1 && in_array($left[0], $ids1, true));
        }
    }

    echo "scan_identity_php: $n checks, $fail failure(s)\n";
    exit($fail ? 1 : 0);
}
