<?php
/**
 * CheckCharacter — faithful PHP port of the check-character engine.
 *
 * Ported line-for-line from the source of truth
 *   qrcode_generation/check_characters.py
 * in the qrcode_generation repository. Correctness is proven, not asserted:
 * tests/parity_php.php recomputes every row of tests/check_fixture.json (the
 * fixture generated by the Python engine) and fails on any mismatch. That makes
 * PHP a verified fourth runtime alongside Python, JavaScript, and Excel/VBA.
 *
 * Used by the module's server-side guard (redcap_save_record) so an invalid ID
 * is caught even when it arrives via the API or data import, where client-side
 * JavaScript never runs.
 */

namespace INSPIRE\UniversalValidator;

class CheckCharacter
{
    const DIGITS    = '0123456789';
    const LETTERS26 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const ALNUM36   = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';

    // Named weighted-modulus schemes — a byte-for-byte copy of WEIGHTED_SCHEMES
    // in the Python source of truth (qrcode_generation/check_characters.py) and
    // the JS engine (js/engine.js). Adding a scheme is one row here plus the same
    // row in those two ports; nothing else in this file changes. All emit one
    // check character over a digit payload.
    const WEIGHTED_SCHEMES = [
        'gs1_mod10'      => ['modulus' => 10, 'mode' => 'cycle',  'weights' => [3, 1],
                             'from' => 'right', 'complement' => true,  'checkAlphabet' => self::DIGITS],
        'aba_mod10'      => ['modulus' => 10, 'mode' => 'cycle',  'weights' => [3, 7, 1],
                             'from' => 'left',  'complement' => true,  'checkAlphabet' => self::DIGITS],
        'mrz_mod10'      => ['modulus' => 10, 'mode' => 'cycle',  'weights' => [7, 3, 1],
                             'from' => 'left',  'complement' => false, 'checkAlphabet' => self::DIGITS],
        'weighted_mod11' => ['modulus' => 11, 'mode' => 'linear', 'start' => 2, 'step' => 1,
                             'from' => 'right', 'complement' => true,  'checkAlphabet' => self::DIGITS . 'X'],
    ];

    // Hard caps that bound the pooled parser's work per keystroke (client) and
    // per save (server). A rule beyond them is a config error at settings-save
    // time and "unconfigurable" at runtime — never silently expensive. The JS
    // engine mirrors these as literals (js/engine.js, QRID_MAX_* block); keep
    // the two in sync.
    const MAX_ID_LEN      = 64;   // longest single ID/member the parser will consider
    const MAX_LEN_CHOICES = 32;   // most candidate lengths a pooled rule may declare
    const MAX_EXPECTED_IDS = 9999;
    const MAX_KEEP_CHARS  = 64;
    const MAX_POOLED_LEN  = 4096; // absolute pooled scan cap (client QRID_MAX_POOLED_LEN)
    // One pooled parse costs about (scanned length) x |LENS| x (member length)
    // char-ops; this budget bounds the product for every legal config, so an
    // expensive rule shrinks its scan cap instead of stalling the save hook.
    const POOLED_WORK_BUDGET = 2000000;
    // Config-time bound on BOUNDED-quantifier backtracking (riskyPattern stage
    // two-b). A contiguous run of overlapping bounded repeats (A{1,20}A{1,20}…)
    // backtracks with the factor count as the exponent, so a long chain freezes a
    // browser's engine even though each factor is bounded and PCRE2 auto-
    // possessifies it — and the client has no match-time backstop the server's
    // preg_last_error guard provides. Refuse a run whose product of per-factor
    // match-length choices exceeds this. Chosen (measured) so the deliberate
    // 3-factor residue A{1,40}A{1,40}A{1,40}9 (= 64000) still passes and a browser-
    // freezing chain (≥5 factors of {1,20} = 3.2M) does not; the worst admitted
    // case measures ~40 ms. Keep in sync with QRID_MAX_BACKTRACK_PRODUCT (js).
    const MAX_BACKTRACK_PRODUCT = 1000000;

    /** Number of check characters an algorithm appends. */
    public static function nCheckChars($name)
    {
        if ($name === 'none') return 0;
        if ($name === 'iso7064_mod97_10' || $name === 'iso7064_letters2') return 2;
        return 1;
    }

    /**
     * Return ONLY the check character(s) for a prepared payload.
     * Mirrors CheckCharacterAlgorithm.compute in the Python engine.
     */
    public static function compute($name, $payload)
    {
        if (isset(self::WEIGHTED_SCHEMES[$name])) {
            return self::weighted($payload, self::WEIGHTED_SCHEMES[$name]);
        }
        switch ($name) {
            case 'iso7064_mod11_2':  return self::pure($payload, self::DIGITS,  11, 2, 1, self::DIGITS . 'X');
            case 'iso7064_mod37_2':  return self::pure($payload, self::ALNUM36, 37, 2, 1, self::ALNUM36 . '*');
            case 'iso7064_mod97_10': return self::pure($payload, self::DIGITS,  97, 10, 2, self::DIGITS);
            case 'iso7064_mod11_10': return self::hybrid($payload, self::DIGITS);
            case 'iso7064_mod37_36': return self::hybrid($payload, self::ALNUM36);
            case 'iso7064_letters1': return self::letters1($payload);
            case 'iso7064_letters2': return self::letters2($payload);
            case 'damm':             return self::damm($payload);
            case 'verhoeff':         return self::verhoeff($payload);
            case 'luhn':             return self::luhn($payload);
            case 'none':             return '';
            default:
                throw new \InvalidArgumentException("unknown check algorithm: $name");
        }
    }

    // -- normalization + source extraction (mirror check_characters.py) ------

    /**
     * Unicode dash folding + uppercase + delimiter strip.
     *
     * Multibyte-safe throughout so the server verdict matches the browser
     * engine (js/engine.js), which normalizes with Unicode-aware primitives
     * (String.toUpperCase, Array.from, /\p{Nd}/u). Uses mb_strtoupper for case
     * folding and code-point splitting for strip/keep_only so a non-ASCII
     * character is never mangled into raw bytes.
     */
    public static function normalize($value, $strip = "-/ _|\\", $uppercase = true, $unifyDashes = true, $keepOnly = null)
    {
        $s = (string) $value;
        if ($unifyDashes) {
            $s = str_replace(
                ["\u{2010}", "\u{2011}", "\u{2012}", "\u{2013}", "\u{2014}", "\u{2015}", "\u{2212}"],
                '-',
                $s
            );
        }
        if ($uppercase) {
            $s = mb_strtoupper($s, 'UTF-8');
        }
        if ($strip !== null && $strip !== '') {
            // Split the strip set by code point (not byte) so a multibyte
            // delimiter is removed as a whole character, never byte-by-byte.
            $stripChars = preg_split('//u', $strip, -1, PREG_SPLIT_NO_EMPTY);
            if ($stripChars) $s = str_replace($stripChars, '', $s);
        }
        if ($keepOnly !== null) {
            $keep = array_flip(preg_split('//u', $keepOnly, -1, PREG_SPLIT_NO_EMPTY) ?: []);
            $out = '';
            foreach (preg_split('//u', $s, -1, PREG_SPLIT_NO_EMPTY) ?: [] as $ch) {
                if (isset($keep[$ch])) $out .= $ch;
            }
            $s = $out;
        }
        return $s;
    }

    /**
     * Extract the substring the algorithm runs over.
     *
     * Unicode-aware (\p{Nd}) to mirror the browser engine: a non-ASCII decimal
     * digit is KEPT here, then rejected downstream by the ASCII algorithm
     * alphabet — exactly as the JS side behaves. ASCII \d/\D would silently
     * strip such a character and flip the verdict, breaking client/server parity.
     */
    public static function applySource($norm, $source)
    {
        if ($source === 'digits_only')   return preg_replace('/[^\p{Nd}]/u', '', $norm);
        if ($source === 'sequence_only') return preg_match('/(\p{Nd}+)\P{Nd}*$/u', $norm, $m) ? $m[1] : '';
        return $norm; // normalized_id (default)
    }

    /**
     * Validate a full (check-bearing) ID: normalize, peel the check character(s),
     * apply the source to the remainder, recompute and compare. Returns true for
     * the "none" algorithm (no check character to verify).
     */
    public static function validateId($algo, $source, $strip, $fullRaw)
    {
        if ($algo === 'none') return true;
        try {
            $norm = self::normalize($fullRaw, $strip);
            $n = self::nCheckChars($algo);
            if ($n <= 0) return true;
            // Code-point (not byte) length/slicing so peeling the check
            // character(s) matches the browser engine on multibyte input.
            $len = mb_strlen($norm, 'UTF-8');
            if ($len <= $n) return false;
            $body  = mb_substr($norm, 0, $len - $n, 'UTF-8');
            $check = mb_substr($norm, $len - $n, null, 'UTF-8');
            $payload = self::applySource($body, $source);
            if ($payload === '') return false;
            return self::compute($algo, $payload) === $check;
        } catch (\Throwable $e) {
            return false; // out-of-alphabet character etc. -> not valid
        }
    }

    /**
     * Mint an ID: append the computed check character(s) to the RAW value.
     * Mirrors the browser engine's appendCheck (QRCheck.appendCheck): the check
     * is computed over the normalized payload but appended to the raw string so
     * any separators the user typed are preserved. When placement is
     * "append_after_delimiter" the check is separated from the body by $delimiter,
     * exactly as the JS side does. Used by the parity harness to verify the
     * append/validate scheme operations, not by the runtime guard.
     */
    public static function appendCheck($algo, $source, $strip, $raw, $placement = 'append', $delimiter = '-')
    {
        if ($algo === 'none') return (string) $raw;
        $norm = self::normalize($raw, $strip);
        $payload = self::applySource($norm, $source);
        if ($payload === '') {
            throw new \InvalidArgumentException('ID normalizes to empty; nothing to compute a check over');
        }
        $chk = self::compute($algo, $payload);
        if ($chk === '') return (string) $raw;
        if ($placement === 'append_after_delimiter') return (string) $raw . $delimiter . $chk;
        return (string) $raw . $chk;
    }

    // -- server-side rule validation (mirror the browser rule semantics) -----

    /** The check alphabet an algorithm emits into (mirrors the JS registry). */
    public static function checkAlphabet($name)
    {
        if (isset(self::WEIGHTED_SCHEMES[$name])) {
            return self::WEIGHTED_SCHEMES[$name]['checkAlphabet'];
        }
        switch ($name) {
            case 'iso7064_mod11_2':  return self::DIGITS . 'X';
            case 'iso7064_mod37_2':  return self::ALNUM36 . '*';
            case 'iso7064_mod97_10': return self::DIGITS;
            case 'iso7064_mod11_10': return self::DIGITS;
            case 'iso7064_mod37_36': return self::ALNUM36;
            case 'iso7064_letters1': return self::LETTERS26;
            case 'iso7064_letters2': return 'ABCDEF';
            case 'damm':             return self::DIGITS;
            case 'verhoeff':         return self::DIGITS;
            case 'luhn':             return self::DIGITS;
            default:                 return '';
        }
    }

    /**
     * Conservative catastrophic-backtracking detector — the PHP twin of the
     * browser's QRID_riskyPattern (js/engine.js). Two stages, both at config
     * time. Stage one rejects the EXPONENTIAL shapes: nested quantifiers AND any
     * repetition of a group that can match the same text more than one way
     * (alternation, optionals, or inner quantifiers) — (a|aa)+, (a?)+ and
     * ((a)|(aa))+ are refused, not only (a+)+ — collapsing inner groups layer by
     * layer so nesting cannot hide the shape. Stage two (polynomialOverlap)
     * rejects the POLYNOMIAL shapes stage one misses: two or more unbounded
     * quantifiers over overlapping character classes with no mandatory separator
     * between them (.*.*, [0-9]*[0-9]*, [A-Z]+[A-Z0-9]+). Those do not blow up on
     * PCRE2 (it auto-possessifies) but freeze a browser's backtracking engine,
     * so the client needs them refused before they are ever run. Genuinely
     * linear shapes — disjoint adjacent classes ([A-Z]+[0-9]+) and a mandatory
     * separator (.*x.*) — are admitted. Still a heuristic, not a safety proof: it
     * over-rejects, and the match-time PCRE-error guard remains the server
     * backstop for the bounded residue (e.g. A{1,40}A{1,40}A{1,40}9). Keep in
     * exact sync with the JS version; tests/risky_php.php and tests/risky_js.cjs
     * assert the two agree on a shared pattern list.
     */
    public static function riskyPattern($src)
    {
        if (mb_strlen((string) $src, 'UTF-8') > 512) return true;           // absurd pattern source
        $s = preg_replace('/\\\\./', '', (string) $src);                    // ignore escaped chars
        $s = preg_replace('/\(\?(<?[=!]|:)/', '(', $s);                     // (?: (?= (?! (?<= (?<! -> plain (
        // Whitespace is an explicit ASCII class, NOT \s: PCRE \s (no /u) and JS \s
        // classify Unicode whitespace differently, which would diverge. Bounded
        // quantifiers ({n,m}/{n,}) count as the "repeating" token so nested bounded
        // quantifiers are caught too. Keep BYTE-IDENTICAL to QRID_riskyPattern (js).
        for (;;) {
            if (preg_match('/[+*][ \t\n\r\f]*[*+{]/', $s)) return true;                                        // a++  a*+  a*{2} ...
            if (preg_match('/\([^()]*(?:[*+]|\{[0-9]+,[0-9]*\})[^()]*\)[ \t\n\r\f]*[*+{?]/', $s)) return true; // (…a+…)+  (…{1,20}…){1,20}
            if (preg_match('/\[[^\]]*\][ \t\n\r\f]*[*+][ \t\n\r\f]*[*+{]/', $s)) return true;                  // [0-9]+* style
            // Collapse every innermost group: a body that can match more than one
            // way (alternation, optional, variable-length content) becomes a
            // variable-length token X*; a fixed body becomes the single token A.
            // A repetition of a variable token is then caught by the rules above
            // on the next pass — (a|aa)+ -> X*+ -> rule 1.
            $t = preg_replace_callback('/\(([^()]*)\)/', function ($m) {
                return (preg_match('/[|?*+]/', $m[1]) || preg_match('/\{[0-9]+,[0-9]*\}/', $m[1])) ? 'X*' : 'A';
            }, $s);
            if ($t === $s) break;
            $s = $t;
        }
        // Stage two: the polynomial-overlap class the exponential rules miss.
        if (self::polynomialOverlap($s)) return true;   // .*.*  [0-9]*[0-9]*  [A-Z]+[A-Z0-9]+
        return false;
    }

    /**
     * Reject two or more unbounded quantifiers (*, +, {n,}) whose atoms have
     * overlapping character sets with no mandatory atom pinning a split between
     * them — the polynomial-backtracking class stage one lets through. Operates
     * on $s AFTER escape-stripping, lookaround-unwrapping, and the group-collapse
     * loop above (so groups are already reduced to A / X* tokens; two repeats of
     * the same collapsed group therefore read as overlapping too). Assumes an
     * ASCII pattern source, which the server match path enforces elsewhere. Keep
     * behavior in sync with QRID_polyOverlap (js).
     */
    private static function polynomialOverlap($s)
    {
        $toks = self::tokenizePattern($s);
        $m = count($toks);
        for ($i = 0; $i < $m; $i++) {
            if (!$toks[$i]['unbounded']) continue;
            for ($j = $i + 1; $j < $m; $j++) {
                if ($toks[$j]['unbounded'] && self::classesOverlap($toks[$i]['cls'], $toks[$j]['cls'])) {
                    return true;
                }
                if ($toks[$j]['mandatory']) break;   // a must-match atom anchors the split point
            }
        }
        // Stage two-b: the BOUNDED-quantifier chain (F1). A contiguous run of
        // overlapping bounded repeats (A{1,20}A{1,20}…) backtracks with the factor
        // count as the exponent — bounded per factor, but still a browser tab
        // freeze past ~5 factors, and the client has no match-time guard. Bound
        // the product of per-factor match-length choices; a fixed atom (choices 1),
        // an unbounded quantifier, or a disjoint class ends the run and anchors a
        // split. A single quantifier (or the deliberate 3-factor residue) stays
        // under the budget. Twin of QRID_polyOverlap stage two-b (js).
        for ($a = 0; $a < $m; $a++) {
            if ($toks[$a]['choices'] < 2) continue;
            $prod = $toks[$a]['choices'];
            for ($b = $a + 1; $b < $m; $b++) {
                if ($toks[$b]['choices'] < 2) break;                                     // fixed atom / unbounded ends the run
                if (!self::classesOverlap($toks[$a]['cls'], $toks[$b]['cls'])) break;    // a disjoint repeat ends it
                $prod *= $toks[$b]['choices'];
                if ($prod > self::MAX_BACKTRACK_PRODUCT) return true;
            }
        }
        return false;
    }

    /**
     * Split a normalized pattern into atoms, each carrying its character set and
     * quantifier facts. cls === null means "universal" (a '.', or a collapsed
     * group token whose contents are unknown — treated as overlapping everything,
     * conservatively). unbounded = the quantifier has no upper limit (*, +, {n,}).
     * mandatory = it must consume at least one character (bare atom, +, {n>=1}).
     */
    private static function tokenizePattern($s)
    {
        $toks = [];
        $n = strlen($s);
        $i = 0;
        while ($i < $n) {
            $c = $s[$i];
            $cls = null;
            if ($c === '.') { $cls = null; $i++; }
            elseif ($c === '[') {
                $close = strpos($s, ']', $i + 1);
                if ($close === false) { $i++; continue; }   // unterminated class: skip the '['
                $cls = self::expandClass(substr($s, $i + 1, $close - $i - 1));
                $i = $close + 1;
            }
            elseif (strpos('^$*+?{}|()', $c) !== false) { $i++; continue; }   // anchors / stray metachars: not atoms
            else { $cls = $c; $i++; }                                          // a literal char (incl. A / X collapse tokens)
            // read the quantifier that follows this atom. `choices` = the number
            // of distinct match-lengths the atom can take (its backtracking slack):
            // 1 for a bare atom or a fixed {n}, 2 for ?, (hi-lo+1) for {lo,hi};
            // an unbounded quantifier is handled by stage two-a, not the product.
            $unbounded = false; $mandatory = true; $choices = 1;   // a bare atom must match once
            if ($i < $n) {
                $q = $s[$i];
                if ($q === '*') { $unbounded = true; $mandatory = false; $i++; }
                elseif ($q === '+') { $unbounded = true; $mandatory = true; $i++; }
                elseif ($q === '?') { $unbounded = false; $mandatory = false; $choices = 2; $i++; }
                elseif ($q === '{') {
                    $close = strpos($s, '}', $i + 1);
                    if ($close !== false && preg_match('/^([0-9]*)(,?)([0-9]*)$/', substr($s, $i + 1, $close - $i - 1), $mm)) {
                        $lo = $mm[1] === '' ? 0 : (int) $mm[1];
                        $unbounded = ($mm[2] === ',') && ($mm[3] === '');   // {n,} unbounded; {n} / {n,m} bounded
                        $mandatory = $lo >= 1;
                        if (!$unbounded) {
                            $hi = ($mm[3] === '') ? $lo : (int) $mm[3];      // {n} -> hi=lo (choices 1)
                            $choices = $hi - $lo + 1;
                            if ($choices < 1) $choices = 1;                  // malformed {5,2}: PCRE rejects it anyway
                        }
                        $i = $close + 1;
                    }
                }
            }
            $toks[] = ['cls' => $cls, 'unbounded' => $unbounded, 'mandatory' => $mandatory, 'choices' => $choices];
        }
        return $toks;
    }

    /** Expand a bracket-class body to its literal ASCII members; null = universal. */
    private static function expandClass($inner)
    {
        if ($inner === '') return '';                // matches nothing
        if ($inner[0] === '^') return null;          // negated class: large -> universal
        $out = '';
        $len = strlen($inner);
        $k = 0;
        while ($k < $len) {
            if ($k + 2 < $len && $inner[$k + 1] === '-') {
                $lo = ord($inner[$k]); $hi = ord($inner[$k + 2]);
                if ($lo <= $hi && $hi - $lo <= 255) {
                    for ($x = $lo; $x <= $hi; $x++) $out .= chr($x);
                    $k += 3; continue;
                }
            }
            $out .= $inner[$k]; $k++;
        }
        return $out;
    }

    /** Do two character sets share a member? null = universal (overlaps all). */
    private static function classesOverlap($a, $b)
    {
        if ($a === null || $b === null) return true;
        if ($a === '' || $b === '') return false;
        $len = strlen($a);
        for ($k = 0; $k < $len; $k++) {
            if (strpos($b, $a[$k]) !== false) return true;
        }
        return false;
    }

    /**
     * Test a value against a project ID regex (JavaScript-authored, anchored).
     * The value is normalized the way the browser tests format — uppercase +
     * unified dashes, separators KEPT. Returns true (i.e. "do not raise a format
     * error the client would not") when the pattern is catastrophic, when the
     * regex cannot be compiled server-side (JS/PCRE dialect gap), or when the PCRE
     * engine itself fails at match time (backtrack/recursion limit) — a PCRE
     * failure is not a real format mismatch and must never be logged as one.
     */
    public static function matchesPattern($value, $pattern)
    {
        if ($pattern === null || $pattern === '') return true;
        if (self::riskyPattern($pattern)) return true;      // never run a catastrophic pattern
        $norm = trim(self::normalize($value, '', true, true, null));
        // JS RegExp (UTF-16 code units) and PCRE /u (code points) count a
        // non-ASCII character differently — e.g. an astral emoji is two units
        // to the browser and one to PCRE, so "." patterns flip verdicts. The
        // proven parity subset is printable ASCII; outside it the server must
        // fail OPEN (no format log) rather than risk logging a mismatch the
        // client never showed (COR-004).
        if (preg_match('/[^\x20-\x7E]/', $norm)) return true;
        $body = preg_replace('/^\^/', '', (string) $pattern);
        $body = preg_replace('/\$$/', '', $body);
        $re = self::compilePattern($body);
        if ($re === null) return true;
        $m = @preg_match($re, $norm);
        if ($m === false || preg_last_error() !== PREG_NO_ERROR) return true; // engine error, not a format miss
        return $m === 1;
    }

    /** True iff the (JS-style) pattern compiles as an anchored PCRE. */
    public static function patternCompiles($pattern)
    {
        $body = preg_replace('/^\^/', '', (string) $pattern);
        $body = preg_replace('/\$$/', '', $body);
        return self::compilePattern($body) !== null;
    }

    /** Build an anchored PCRE from a JS-style regex body, or null if uncompilable. */
    private static function compilePattern($body)
    {
        $delims = ['/', '#', '~', '!', '@', '%', ';', ':', '|', '='];
        $d = null;
        foreach ($delims as $cand) {
            if (strpos($body, $cand) === false) { $d = $cand; break; }
        }
        if ($d === null) { $d = '/'; $body = str_replace('/', '\\/', $body); }
        $re = $d . '^(?:' . $body . ')$' . $d . 'u';
        return (@preg_match($re, '') === false) ? null : $re;
    }

    /**
     * True iff $t matches the compiled pattern. On a PCRE ENGINE failure
     * (backtrack/recursion limit — possible for a catastrophic pattern the
     * heuristic missed) it flags the run so the whole pooled field bails to
     * "unconfigurable" instead of silently dropping the window into a false
     * junk / invalid-ID verdict. Mirrors the preg_last_error guard in
     * matchesPattern() for the single-field path.
     */
    private static function patTest($re, $t)
    {
        $m = @preg_match($re, $t);
        if ($m === false || preg_last_error() !== PREG_NO_ERROR) {
            self::$pooledPcreError = true;
            return false;
        }
        return $m === 1;
    }

    /**
     * Server-side single-field validation mirroring the client's rule order:
     * format (idPattern) first, then check character. Returns ['ok', 'reason'].
     */
    public static function validateSingleField($algo, $source, $strip, $pattern, $value)
    {
        $hasPattern = ($pattern !== null && $pattern !== '');
        if ($hasPattern && !self::matchesPattern($value, $pattern)) {
            return ['ok' => false, 'reason' => 'format'];
        }
        if ($algo !== 'none') {
            if (!self::validateId($algo, $source, $strip, $value)) {
                return ['ok' => false, 'reason' => 'check-character'];
            }
            return ['ok' => true, 'reason' => 'valid'];
        }
        // algorithm "none": format-only if a pattern is set, otherwise nothing to check.
        return ['ok' => true, 'reason' => $hasPattern ? 'valid' : 'no-op'];
    }

    // -- server-side pooled parser (faithful port of QRIDPooledInit) ---------
    //
    // Behavior is frozen against tests/pooled_fixture.json, recomputed by BOTH
    // runtimes in CI, so the server parser can never drift from the browser one.

    /** Set true when a PCRE engine failure occurs during a pooled parse, so the
     *  whole field bails to "unconfigurable" rather than emitting a false verdict. */
    private static $pooledPcreError = false;

    private static function isPosInt($x)
    {
        if (is_int($x)) return $x > 0;
        if (is_string($x)) return ctype_digit($x) && (int) $x > 0;
        return is_numeric($x) && $x > 0 && floor($x) == $x;
    }

    /** Resolve LENS / KEEP / regex from a pooled rule config, or null if unsafe. */
    private static function pooledState(array $cfg)
    {
        $ALPHA  = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
        $algo   = (isset($cfg['algorithm']) && $cfg['algorithm'] !== '') ? $cfg['algorithm'] : 'iso7064_mod37_36';
        $source = (isset($cfg['source']) && $cfg['source'] !== '') ? $cfg['source'] : 'normalized_id';
        $strip  = (array_key_exists('strip', $cfg) && $cfg['strip'] !== null) ? $cfg['strip'] : '';
        $pattern = (isset($cfg['idPattern']) && $cfg['idPattern'] !== '') ? $cfg['idPattern'] : null;

        $checkMode = ($algo !== 'none');
        $regexOnly = (!$checkMode && $pattern !== null);
        if (!$checkMode && !$regexOnly) return null; // nothing to validate
        if ($pattern !== null && self::riskyPattern($pattern)) return null; // catastrophic -> unconfigurable

        $re = null;
        if ($pattern !== null) {
            $body = preg_replace('/^\^/', '', (string) $pattern);
            $body = preg_replace('/\$$/', '', $body);
            $re = self::compilePattern($body);
            if ($re === null) return null; // cannot segment safely
        }

        $nCheck = $checkMode ? self::nCheckChars($algo) : 0;

        $LENS = [];
        $minLen = (isset($cfg['idMinLen']) && $cfg['idMinLen'] !== null && $cfg['idMinLen'] !== '') ? (int) $cfg['idMinLen'] : 8;
        $maxLen = (isset($cfg['idMaxLen']) && $cfg['idMaxLen'] !== null && $cfg['idMaxLen'] !== '') ? (int) $cfg['idMaxLen'] : 14;
        if (isset($cfg['idLengths']) && $cfg['idLengths'] !== null) {
            $lens = $cfg['idLengths'];
            if (!is_array($lens) || !count($lens)) return null;
            foreach ($lens as $L) if (!self::isPosInt($L)) return null;
            $lens = array_values(array_unique(array_map('intval', $lens)));
            sort($lens);
            $set = array_flip($lens);
            foreach ($lens as $a) foreach ($lens as $b) if (isset($set[$a + $b])) return null; // sum-swallow
            $LENS = $lens;
            $minLen = $lens[0];
            $maxLen = $lens[count($lens) - 1];
        } else {
            if (!self::isPosInt($minLen) || !self::isPosInt($maxLen)) return null;
            if ($maxLen < $minLen) return null;
            if ($maxLen >= 2 * $minLen) return null;
            if ($maxLen > self::MAX_ID_LEN) return null; // BEFORE the range loop: no huge allocation
            $minLen = max($minLen, $nCheck + 1);
            for ($L = $minLen; $L <= $maxLen; $L++) $LENS[] = $L;
        }
        // Hard work bounds: parsing tests every candidate length at every
        // position, so unbounded lengths turn one keystroke/save into seconds
        // of regex + check-character work (PER-002). Beyond the caps the rule
        // is unconfigurable (and rejected at settings-save time upstream).
        if ($maxLen > self::MAX_ID_LEN || count($LENS) > self::MAX_LEN_CHOICES) return null;

        $keepCfg = isset($cfg['keepChars']) ? (string) $cfg['keepChars'] : '';
        // Non-ASCII keep characters would make the byte-indexed splitter below
        // disagree with the browser's UTF-16 one; the audited subset is ASCII.
        if (strlen($keepCfg) > self::MAX_KEEP_CHARS || preg_match('/[^\x20-\x7E]/', $keepCfg)) return null;

        $KEEP = $ALPHA . $keepCfg;
        if ($checkMode) {
            $CA = self::checkAlphabet($algo);
            for ($i = 0; $i < strlen($CA); $i++) {
                if (strpos($KEEP, $CA[$i]) === false) $KEEP .= $CA[$i];
            }
        }
        if ($pattern !== null) {
            $pat = (string) $pattern; $meta = '\\^$.|?*+()[]{}';
            for ($i = 0; $i < strlen($pat); $i++) {
                $pc = $pat[$i];
                if ($pc === '\\') {
                    $i++;
                    if ($i < strlen($pat)) {
                        $pc = $pat[$i];
                        if (strpos($meta, $pc) !== false && strpos($KEEP, $pc) === false) $KEEP .= $pc;
                    }
                    continue;
                }
                if (strpos($meta, $pc) === false && !preg_match('/[A-Za-z0-9]/', $pc) && strpos($KEEP, $pc) === false) {
                    $KEEP .= $pc;
                }
            }
        }

        return [
            'algo' => $algo, 'source' => $source, 'strip' => $strip,
            'checkMode' => $checkMode, 'regexOnly' => $regexOnly, 'nCheck' => $nCheck,
            'minLen' => $minLen, 'maxLen' => $maxLen, 'LENS' => $LENS, 'KEEP' => $KEEP, 're' => $re,
        ];
    }

    private static function pooledVerifies(array $st, $t)
    {
        if ($st['re'] !== null && !self::patTest($st['re'], $t)) return false;
        if ($st['regexOnly']) return true;
        return self::validateId($st['algo'], $st['source'], $st['strip'], $t);
    }

    private static function pooledBetter(array $a, array $b)
    {
        if ($a['tok'] !== $b['tok']) return $a['tok'] > $b['tok'];
        if ($a['runs'] !== $b['runs']) return $a['runs'] < $b['runs'];
        if ($a['maxL'] !== $b['maxL']) return $a['maxL'] < $b['maxL'];
        return $a['chars'] > $b['chars'];
    }

    private static function pooledSegments(array $st, $raw)
    {
        $s = self::normalize($raw, '', true, true, $st['KEEP']); // clean(): keep only KEEP chars
        $N = strlen($s);
        $LENS = $st['LENS'];
        $sc = array_fill(0, $N + 1, null);
        $sc[$N] = ['tok' => 0, 'maxL' => 0, 'runs' => 0, 'chars' => 0, 'startsJunk' => false, 'move' => -1];
        for ($i = $N - 1; $i >= 0; $i--) {
            $c = $sc[$i + 1];
            $best = [
                'tok' => $c['tok'], 'maxL' => $c['maxL'],
                'runs' => $c['runs'] + ($c['startsJunk'] ? 0 : 1),
                'chars' => $c['chars'] + 1, 'startsJunk' => true, 'move' => 0,
            ];
            foreach ($LENS as $L) {
                if ($L > $N - $i) break;
                if (!self::pooledVerifies($st, substr($s, $i, $L))) continue;
                $ch = $sc[$i + $L];
                $cand = [
                    'tok' => $ch['tok'] + 1, 'maxL' => ($L > $ch['maxL'] ? $L : $ch['maxL']),
                    'runs' => $ch['runs'], 'chars' => $ch['chars'], 'startsJunk' => false, 'move' => $L,
                ];
                if (self::pooledBetter($cand, $best)) $best = $cand;
            }
            $sc[$i] = $best;
        }
        $segs = []; $pos = 0; $junk = '';
        while ($pos < $N) {
            $m = $sc[$pos]['move'];
            if ($m > 0) {
                if ($junk !== '') { $segs[] = ['type' => 'junk', 'text' => $junk]; $junk = ''; }
                $segs[] = ['type' => 'id', 'id' => substr($s, $pos, $m), 'valid' => true];
                $pos += $m;
            } else {
                $junk .= $s[$pos]; $pos++;
            }
        }
        if ($junk !== '') $segs[] = ['type' => 'junk', 'text' => $junk];

        // re-scan junk for well-formed-but-wrong-check members (check + pattern only)
        if ($st['re'] !== null && $st['checkMode']) {
            $out = [];
            foreach ($segs as $seg) {
                if ($seg['type'] !== 'junk') { $out[] = $seg; continue; }
                $rest = $seg['text']; $buf = '';
                while (strlen($rest)) {
                    $hit = '';
                    $lim2 = min($st['maxLen'], strlen($rest));
                    for ($L2 = $st['minLen']; $L2 <= $lim2 && $hit === ''; $L2++) {
                        if (self::patTest($st['re'], substr($rest, 0, $L2))) $hit = substr($rest, 0, $L2);
                    }
                    if ($hit !== '') {
                        if ($buf !== '') { $out[] = ['type' => 'junk', 'text' => $buf]; $buf = ''; }
                        $out[] = ['type' => 'id', 'id' => $hit, 'valid' => false];
                        $rest = substr($rest, strlen($hit));
                    } else {
                        $buf .= $rest[0]; $rest = substr($rest, 1);
                    }
                }
                if ($buf !== '') $out[] = ['type' => 'junk', 'text' => $buf];
            }
            $segs = $out;
        }
        return $segs;
    }

    /**
     * Segment a pooled field into members + junk. Returns a list of
     *   ['type'=>'id','id'=>..,'valid'=>bool]  or  ['type'=>'junk','text'=>..]
     * or null when the config is unsafe (client shows a config error instead).
     */
    /** Per-rule scan cap — the PHP twin of the client's SCAN_CAP formula. */
    public static function pooledScanCap(array $st)
    {
        $lens = count($st['LENS']) ?: 1;
        $max  = $st['maxLen'] ?: 1;
        $cap  = (int) floor(self::POOLED_WORK_BUDGET / ($lens * $max));
        if ($cap < 256) $cap = 256;
        return min(self::MAX_POOLED_LEN, $cap);
    }

    public static function pooledParse(array $cfg, $raw)
    {
        $st = self::pooledState($cfg);
        if ($st === null) return null;
        // Over-budget input: no verdict at all, never a slow parse — the client
        // bails identically at the same cap, so the runtimes cannot disagree.
        if (mb_strlen((string) $raw, 'UTF-8') > self::pooledScanCap($st)) return null;
        self::$pooledPcreError = false;
        $segs = self::pooledSegments($st, (string) $raw);
        // A PCRE engine failure during segmentation makes the result untrustworthy;
        // treat the field as unconfigurable (no verdict) rather than log a false one.
        return self::$pooledPcreError ? null : $segs;
    }

    /** Server-side pooled verdict mirroring the browser render() problem checks. */
    public static function validatePooledField(array $cfg, $raw)
    {
        $segs = self::pooledParse($cfg, $raw);
        if ($segs === null) return ['ok' => true, 'reason' => 'unconfigurable', 'count' => 0];
        $ids = 0; $junk = 0; $bad = 0; $dups = 0; $seen = [];
        foreach ($segs as $seg) {
            if ($seg['type'] === 'id') {
                $ids++;
                if (!$seg['valid']) $bad++;
                if (isset($seen[$seg['id']])) $dups++;
                $seen[$seg['id']] = true;
            } else {
                $junk++;
            }
        }
        $problems = [];
        if (!$ids) $problems[] = 'no-id';
        if ($bad)  $problems[] = 'check-character';
        if ($junk) $problems[] = 'junk';
        if ($dups) $problems[] = 'duplicate';
        $expected = (isset($cfg['expectedIds']) && $cfg['expectedIds']) ? (int) $cfg['expectedIds'] : null;
        if ($expected && $ids !== $expected) $problems[] = 'count';
        return ['ok' => count($problems) === 0, 'reason' => implode(';', $problems), 'count' => $ids];
    }

    // -- engines ------------------------------------------------------------

    private static function idx($alphabet, $ch)
    {
        $i = strpos($alphabet, $ch);
        if ($i === false) {
            throw new \InvalidArgumentException("character '$ch' not in alphabet");
        }
        return $i;
    }

    /** ISO/IEC 7064 pure systems: p = ((p + d) * r) mod M. */
    private static function pure($payload, $alphabet, $M, $r, $n, $checkAlphabet)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $p = 0;
        foreach (str_split($payload) as $ch) {
            $d = self::idx($alphabet, $ch);
            $p = (($p + $d) * $r) % $M;
        }
        for ($k = 0; $k < $n - 1; $k++) {
            $p = ($p * $r) % $M;
        }
        if ($n === 1) {
            $cv = ((1 - $p) % $M + $M) % $M;
            return $checkAlphabet[$cv];
        }
        // Multi-char (Mod 97-10): check value in [2, M+1], NOT reduced mod M;
        // emit n radix-r digits, high digit first, via the payload alphabet.
        $cv = ($M + 1) - $p;
        $digits = [];
        $x = $cv;
        for ($k = 0; $k < $n; $k++) {
            $digits[] = $alphabet[$x % $r];
            $x = intdiv($x, $r);
        }
        return implode('', array_reverse($digits));
    }

    /** ISO/IEC 7064 hybrid systems (Mod n+1,n over the alphabet). */
    private static function hybrid($payload, $alphabet)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $modulus = strlen($alphabet);
        $check = intdiv($modulus, 2);
        foreach (str_split($payload) as $ch) {
            $d = self::idx($alphabet, $ch);
            $check = ((($check ?: $modulus) * 2) % ($modulus + 1) + $d) % $modulus;
        }
        $v = ((1 - (($check ?: $modulus) * 2) % ($modulus + 1)) % $modulus + $modulus) % $modulus;
        return $alphabet[$v];
    }

    /** Hybrid recurrence over pre-mapped values -> check value in [0, modulus). */
    private static function hybridValue($values, $modulus)
    {
        $check = intdiv($modulus, 2);
        foreach ($values as $d) {
            $check = ((($check ?: $modulus) * 2) % ($modulus + 1) + $d) % $modulus;
        }
        return ((1 - (($check ?: $modulus) * 2) % ($modulus + 1)) % $modulus + $modulus) % $modulus;
    }

    /** Letters-only variant 1: fold 36 symbols onto 26 letters, one letter out. */
    private static function letters1($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $vals = [];
        foreach (str_split($payload) as $ch) {
            $vals[] = self::idx(self::ALNUM36, $ch) % 26;
        }
        $v = self::hybridValue($vals, 26);
        $A = self::LETTERS26;
        return $A[$v];
    }

    /** Letters-only variant 2: full Mod 37,36 value as two base-6 letters (A-F). */
    private static function letters2($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $vals = [];
        foreach (str_split($payload) as $ch) {
            $vals[] = self::idx(self::ALNUM36, $ch);
        }
        $v = self::hybridValue($vals, 36);
        $L = 'ABCDEF';
        return $L[intdiv($v, 6)] . $L[$v % 6];
    }

    private static function damm($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        static $T = [
            [0, 3, 1, 7, 5, 9, 8, 6, 4, 2],
            [7, 0, 9, 2, 1, 5, 4, 8, 6, 3],
            [4, 2, 0, 6, 8, 7, 1, 3, 5, 9],
            [1, 7, 5, 0, 9, 8, 3, 4, 2, 6],
            [6, 1, 2, 3, 0, 4, 5, 9, 7, 8],
            [3, 6, 7, 4, 2, 0, 9, 5, 8, 1],
            [5, 8, 6, 9, 7, 2, 0, 1, 3, 4],
            [8, 9, 4, 5, 3, 6, 2, 0, 1, 7],
            [9, 4, 3, 8, 6, 1, 7, 2, 0, 5],
            [2, 5, 8, 1, 4, 3, 6, 7, 9, 0],
        ];
        $interim = 0;
        foreach (str_split($payload) as $ch) {
            $d = self::idx(self::DIGITS, $ch);
            $interim = $T[$interim][$d];
        }
        return (string) $interim;
    }

    private static function verhoeff($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $D = self::verhoeffD();
        $P = self::powerPerm();
        $INV = [0, 4, 3, 2, 1, 5, 6, 7, 8, 9];
        $c = 0;
        foreach (array_reverse(str_split($payload)) as $i => $ch) {
            $d = self::idx(self::DIGITS, $ch);
            $c = $D[$c][$P[($i + 1) % 8][$d]];
        }
        return (string) $INV[$c];
    }

    private static function luhn($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $total = 0;
        foreach (array_reverse(str_split($payload)) as $idx => $ch) {
            $d = self::idx(self::DIGITS, $ch);
            if ($idx % 2 === 0) {
                $d *= 2;
                if ($d > 9) $d -= 9;
            }
            $total += $d;
        }
        return (string) ((10 - ($total % 10)) % 10);
    }

    /**
     * Generic positional weighted-sum modulus check (mirror WeightedModulus in
     * check_characters.py and weightedModulus in js/engine.js). Weights each
     * digit by position, sums, reduces mod M, and maps to the check alphabet.
     * Covers gs1_mod10, aba_mod10, mrz_mod10 and weighted_mod11 from the
     * WEIGHTED_SCHEMES table. Digit payload only.
     */
    private static function weighted($payload, array $spec)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $M = $spec['modulus'];
        $cycle = ($spec['mode'] === 'cycle');
        $weights = $cycle ? $spec['weights'] : null;
        $wlen = $cycle ? count($weights) : 0;
        $fromRight = ($spec['from'] === 'right');
        $chars = str_split($payload);
        $n = count($chars);
        $total = 0;
        for ($i = 0; $i < $n; $i++) {
            $d = self::idx(self::DIGITS, $chars[$i]);
            $pos = $fromRight ? ($n - 1 - $i) : $i;
            $w = $cycle ? $weights[$pos % $wlen] : ($spec['start'] + $spec['step'] * $pos);
            $total += $d * $w;
        }
        $v = $spec['complement'] ? (($M - $total % $M) % $M) : ($total % $M);
        return $spec['checkAlphabet'][$v];
    }

    /** Verhoeff D5 multiplication table. */
    private static function verhoeffD()
    {
        return [
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
            [1, 2, 3, 4, 0, 6, 7, 8, 9, 5],
            [2, 3, 4, 0, 1, 7, 8, 9, 5, 6],
            [3, 4, 0, 1, 2, 8, 9, 5, 6, 7],
            [4, 0, 1, 2, 3, 9, 5, 6, 7, 8],
            [5, 9, 8, 7, 6, 0, 4, 3, 2, 1],
            [6, 5, 9, 8, 7, 1, 0, 4, 3, 2],
            [7, 6, 5, 9, 8, 2, 1, 0, 4, 3],
            [8, 7, 6, 5, 9, 3, 2, 1, 0, 4],
            [9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
        ];
    }

    /** Verhoeff permutation family as successive powers of the base permutation. */
    private static function powerPerm()
    {
        $base = [1, 5, 7, 6, 2, 8, 3, 0, 9, 4];
        $table = [range(0, 9)];
        for ($k = 1; $k < 8; $k++) {
            $prev = $table[$k - 1];
            $row = [];
            for ($x = 0; $x < 10; $x++) {
                $row[] = $base[$prev[$x]];
            }
            $table[] = $row;
        }
        return $table;
    }
}
