<?php
/**
 * CheckCharacter — faithful PHP port of the check-character engine.
 *
 * Ported line-for-line from the source of truth
 *   qrcode_generation/check_characters.py
 * in the qrcode_generation repository. Correctness is proven, not asserted:
 * tests/parity_php.php recomputes every row of tests/check_fixture.json (the
 * fixture generated by the Python engine) and fails on any mismatch. That makes
 * PHP a verified fourth runtime alongside Python, JavaScript, and Excel/VBA.
 *
 * Used by the module's server-side guard (redcap_save_record) so an invalid ID
 * is caught even when it arrives via the API or data import, where client-side
 * JavaScript never runs.
 */

namespace INSPIRE\UniversalValidator;

class CheckCharacter
{
    const DIGITS    = '0123456789';
    const LETTERS26 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const ALNUM36   = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';

    /** Number of check characters an algorithm appends. */
    public static function nCheckChars($name)
    {
        if ($name === 'none') return 0;
        if ($name === 'iso7064_mod97_10' || $name === 'iso7064_letters2') return 2;
        return 1;
    }

    /**
     * Return ONLY the check character(s) for a prepared payload.
     * Mirrors CheckCharacterAlgorithm.compute in the Python engine.
     */
    public static function compute($name, $payload)
    {
        switch ($name) {
            case 'iso7064_mod11_2':  return self::pure($payload, self::DIGITS,  11, 2, 1, self::DIGITS . 'X');
            case 'iso7064_mod37_2':  return self::pure($payload, self::ALNUM36, 37, 2, 1, self::ALNUM36 . '*');
            case 'iso7064_mod97_10': return self::pure($payload, self::DIGITS,  97, 10, 2, self::DIGITS);
            case 'iso7064_mod11_10': return self::hybrid($payload, self::DIGITS);
            case 'iso7064_mod37_36': return self::hybrid($payload, self::ALNUM36);
            case 'iso7064_letters1': return self::letters1($payload);
            case 'iso7064_letters2': return self::letters2($payload);
            case 'damm':             return self::damm($payload);
            case 'verhoeff':         return self::verhoeff($payload);
            case 'luhn':             return self::luhn($payload);
            case 'none':             return '';
            default:
                throw new \InvalidArgumentException("unknown check algorithm: $name");
        }
    }

    // -- normalization + source extraction (mirror check_characters.py) ------

    /**
     * Unicode dash folding + uppercase + delimiter strip.
     *
     * Multibyte-safe throughout so the server verdict matches the browser
     * engine (js/engine.js), which normalizes with Unicode-aware primitives
     * (String.toUpperCase, Array.from, /\p{Nd}/u). Uses mb_strtoupper for case
     * folding and code-point splitting for strip/keep_only so a non-ASCII
     * character is never mangled into raw bytes.
     */
    public static function normalize($value, $strip = "-/ _|\\", $uppercase = true, $unifyDashes = true, $keepOnly = null)
    {
        $s = (string) $value;
        if ($unifyDashes) {
            $s = str_replace(
                ["\u{2010}", "\u{2011}", "\u{2012}", "\u{2013}", "\u{2014}", "\u{2015}", "\u{2212}"],
                '-',
                $s
            );
        }
        if ($uppercase) {
            $s = mb_strtoupper($s, 'UTF-8');
        }
        if ($strip !== null && $strip !== '') {
            // Split the strip set by code point (not byte) so a multibyte
            // delimiter is removed as a whole character, never byte-by-byte.
            $stripChars = preg_split('//u', $strip, -1, PREG_SPLIT_NO_EMPTY);
            if ($stripChars) $s = str_replace($stripChars, '', $s);
        }
        if ($keepOnly !== null) {
            $keep = array_flip(preg_split('//u', $keepOnly, -1, PREG_SPLIT_NO_EMPTY) ?: []);
            $out = '';
            foreach (preg_split('//u', $s, -1, PREG_SPLIT_NO_EMPTY) ?: [] as $ch) {
                if (isset($keep[$ch])) $out .= $ch;
            }
            $s = $out;
        }
        return $s;
    }

    /**
     * Extract the substring the algorithm runs over.
     *
     * Unicode-aware (\p{Nd}) to mirror the browser engine: a non-ASCII decimal
     * digit is KEPT here, then rejected downstream by the ASCII algorithm
     * alphabet — exactly as the JS side behaves. ASCII \d/\D would silently
     * strip such a character and flip the verdict, breaking client/server parity.
     */
    public static function applySource($norm, $source)
    {
        if ($source === 'digits_only')   return preg_replace('/[^\p{Nd}]/u', '', $norm);
        if ($source === 'sequence_only') return preg_match('/(\p{Nd}+)\P{Nd}*$/u', $norm, $m) ? $m[1] : '';
        return $norm; // normalized_id (default)
    }

    /**
     * Validate a full (check-bearing) ID: normalize, peel the check character(s),
     * apply the source to the remainder, recompute and compare. Returns true for
     * the "none" algorithm (no check character to verify).
     */
    public static function validateId($algo, $source, $strip, $fullRaw)
    {
        if ($algo === 'none') return true;
        try {
            $norm = self::normalize($fullRaw, $strip);
            $n = self::nCheckChars($algo);
            if ($n <= 0) return true;
            // Code-point (not byte) length/slicing so peeling the check
            // character(s) matches the browser engine on multibyte input.
            $len = mb_strlen($norm, 'UTF-8');
            if ($len <= $n) return false;
            $body  = mb_substr($norm, 0, $len - $n, 'UTF-8');
            $check = mb_substr($norm, $len - $n, null, 'UTF-8');
            $payload = self::applySource($body, $source);
            if ($payload === '') return false;
            return self::compute($algo, $payload) === $check;
        } catch (\Throwable $e) {
            return false; // out-of-alphabet character etc. -> not valid
        }
    }

    /**
     * Mint an ID: append the computed check character(s) to the RAW value.
     * Mirrors the browser engine's appendCheck (QRCheck.appendCheck): the check
     * is computed over the normalized payload but appended to the raw string so
     * any separators the user typed are preserved. When placement is
     * "append_after_delimiter" the check is separated from the body by $delimiter,
     * exactly as the JS side does. Used by the parity harness to verify the
     * append/validate scheme operations, not by the runtime guard.
     */
    public static function appendCheck($algo, $source, $strip, $raw, $placement = 'append', $delimiter = '-')
    {
        if ($algo === 'none') return (string) $raw;
        $norm = self::normalize($raw, $strip);
        $payload = self::applySource($norm, $source);
        if ($payload === '') {
            throw new \InvalidArgumentException('ID normalizes to empty; nothing to compute a check over');
        }
        $chk = self::compute($algo, $payload);
        if ($chk === '') return (string) $raw;
        if ($placement === 'append_after_delimiter') return (string) $raw . $delimiter . $chk;
        return (string) $raw . $chk;
    }

    // -- server-side rule validation (mirror the browser rule semantics) -----

    /** The check alphabet an algorithm emits into (mirrors the JS registry). */
    public static function checkAlphabet($name)
    {
        switch ($name) {
            case 'iso7064_mod11_2':  return self::DIGITS . 'X';
            case 'iso7064_mod37_2':  return self::ALNUM36 . '*';
            case 'iso7064_mod97_10': return self::DIGITS;
            case 'iso7064_mod11_10': return self::DIGITS;
            case 'iso7064_mod37_36': return self::ALNUM36;
            case 'iso7064_letters1': return self::LETTERS26;
            case 'iso7064_letters2': return 'ABCDEF';
            case 'damm':             return self::DIGITS;
            case 'verhoeff':         return self::DIGITS;
            case 'luhn':             return self::DIGITS;
            default:                 return '';
        }
    }

    /**
     * Conservative catastrophic-backtracking detector — the PHP twin of the
     * browser's QRID_riskyPattern (js/engine.js). Rejects the common exponential
     * shapes (nested / adjacent unbounded quantifiers) so the server never
     * compiles or runs a pattern the browser already refuses at config time. Keep
     * in exact sync with the JS version; tests/risky_php.php and
     * tests/risky_js.cjs assert the two agree on a shared pattern list.
     */
    public static function riskyPattern($src)
    {
        $s = preg_replace('/\\\\./', '', (string) $src);                    // ignore escaped chars
        // Whitespace is an explicit ASCII class, NOT \s: PCRE \s (no /u) and JS \s
        // classify Unicode whitespace differently, which would diverge. Bounded
        // quantifiers ({n,m}/{n,}) count as the "repeating" token so nested bounded
        // quantifiers are caught too. Keep BYTE-IDENTICAL to QRID_riskyPattern (js).
        if (preg_match('/[+*][ \t\n\r\f]*[+*]/', $s)) return true;                                        // a++  a*+ ...
        if (preg_match('/\([^()]*(?:[*+]|\{[0-9]+,[0-9]*\})[^()]*\)[ \t\n\r\f]*[*+{?]/', $s)) return true; // (…a+…)+  (…{1,20}…){1,20}
        if (preg_match('/\[[^\]]*\][ \t\n\r\f]*[*+][ \t\n\r\f]*[*+{]/', $s)) return true;                  // [0-9]+* style
        return false;
    }

    /**
     * Test a value against a project ID regex (JavaScript-authored, anchored).
     * The value is normalized the way the browser tests format — uppercase +
     * unified dashes, separators KEPT. Returns true (i.e. "do not raise a format
     * error the client would not") when the pattern is catastrophic, when the
     * regex cannot be compiled server-side (JS/PCRE dialect gap), or when the PCRE
     * engine itself fails at match time (backtrack/recursion limit) — a PCRE
     * failure is not a real format mismatch and must never be logged as one.
     */
    public static function matchesPattern($value, $pattern)
    {
        if ($pattern === null || $pattern === '') return true;
        if (self::riskyPattern($pattern)) return true;      // never run a catastrophic pattern
        $norm = trim(self::normalize($value, '', true, true, null));
        $body = preg_replace('/^\^/', '', (string) $pattern);
        $body = preg_replace('/\$$/', '', $body);
        $re = self::compilePattern($body);
        if ($re === null) return true;
        $m = @preg_match($re, $norm);
        if ($m === false || preg_last_error() !== PREG_NO_ERROR) return true; // engine error, not a format miss
        return $m === 1;
    }

    /** Build an anchored PCRE from a JS-style regex body, or null if uncompilable. */
    private static function compilePattern($body)
    {
        $delims = ['/', '#', '~', '!', '@', '%', ';', ':', '|', '='];
        $d = null;
        foreach ($delims as $cand) {
            if (strpos($body, $cand) === false) { $d = $cand; break; }
        }
        if ($d === null) { $d = '/'; $body = str_replace('/', '\\/', $body); }
        $re = $d . '^(?:' . $body . ')$' . $d . 'u';
        return (@preg_match($re, '') === false) ? null : $re;
    }

    /**
     * True iff $t matches the compiled pattern. On a PCRE ENGINE failure
     * (backtrack/recursion limit — possible for a catastrophic pattern the
     * heuristic missed) it flags the run so the whole pooled field bails to
     * "unconfigurable" instead of silently dropping the window into a false
     * junk / invalid-ID verdict. Mirrors the preg_last_error guard in
     * matchesPattern() for the single-field path.
     */
    private static function patTest($re, $t)
    {
        $m = @preg_match($re, $t);
        if ($m === false || preg_last_error() !== PREG_NO_ERROR) {
            self::$pooledPcreError = true;
            return false;
        }
        return $m === 1;
    }

    /**
     * Server-side single-field validation mirroring the client's rule order:
     * format (idPattern) first, then check character. Returns ['ok', 'reason'].
     */
    public static function validateSingleField($algo, $source, $strip, $pattern, $value)
    {
        $hasPattern = ($pattern !== null && $pattern !== '');
        if ($hasPattern && !self::matchesPattern($value, $pattern)) {
            return ['ok' => false, 'reason' => 'format'];
        }
        if ($algo !== 'none') {
            if (!self::validateId($algo, $source, $strip, $value)) {
                return ['ok' => false, 'reason' => 'check-character'];
            }
            return ['ok' => true, 'reason' => 'valid'];
        }
        // algorithm "none": format-only if a pattern is set, otherwise nothing to check.
        return ['ok' => true, 'reason' => $hasPattern ? 'valid' : 'no-op'];
    }

    // -- server-side pooled parser (faithful port of QRIDPooledInit) ---------
    //
    // Behavior is frozen against tests/pooled_fixture.json, recomputed by BOTH
    // runtimes in CI, so the server parser can never drift from the browser one.

    /** Set true when a PCRE engine failure occurs during a pooled parse, so the
     *  whole field bails to "unconfigurable" rather than emitting a false verdict. */
    private static $pooledPcreError = false;

    private static function isPosInt($x)
    {
        if (is_int($x)) return $x > 0;
        if (is_string($x)) return ctype_digit($x) && (int) $x > 0;
        return is_numeric($x) && $x > 0 && floor($x) == $x;
    }

    /** Resolve LENS / KEEP / regex from a pooled rule config, or null if unsafe. */
    private static function pooledState(array $cfg)
    {
        $ALPHA  = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
        $algo   = (isset($cfg['algorithm']) && $cfg['algorithm'] !== '') ? $cfg['algorithm'] : 'iso7064_mod37_36';
        $source = (isset($cfg['source']) && $cfg['source'] !== '') ? $cfg['source'] : 'normalized_id';
        $strip  = (array_key_exists('strip', $cfg) && $cfg['strip'] !== null) ? $cfg['strip'] : '';
        $pattern = (isset($cfg['idPattern']) && $cfg['idPattern'] !== '') ? $cfg['idPattern'] : null;

        $checkMode = ($algo !== 'none');
        $regexOnly = (!$checkMode && $pattern !== null);
        if (!$checkMode && !$regexOnly) return null; // nothing to validate
        if ($pattern !== null && self::riskyPattern($pattern)) return null; // catastrophic -> unconfigurable

        $re = null;
        if ($pattern !== null) {
            $body = preg_replace('/^\^/', '', (string) $pattern);
            $body = preg_replace('/\$$/', '', $body);
            $re = self::compilePattern($body);
            if ($re === null) return null; // cannot segment safely
        }

        $nCheck = $checkMode ? self::nCheckChars($algo) : 0;

        $LENS = [];
        $minLen = (isset($cfg['idMinLen']) && $cfg['idMinLen'] !== null && $cfg['idMinLen'] !== '') ? (int) $cfg['idMinLen'] : 8;
        $maxLen = (isset($cfg['idMaxLen']) && $cfg['idMaxLen'] !== null && $cfg['idMaxLen'] !== '') ? (int) $cfg['idMaxLen'] : 14;
        if (isset($cfg['idLengths']) && $cfg['idLengths'] !== null) {
            $lens = $cfg['idLengths'];
            if (!is_array($lens) || !count($lens)) return null;
            foreach ($lens as $L) if (!self::isPosInt($L)) return null;
            $lens = array_values(array_unique(array_map('intval', $lens)));
            sort($lens);
            $set = array_flip($lens);
            foreach ($lens as $a) foreach ($lens as $b) if (isset($set[$a + $b])) return null; // sum-swallow
            $LENS = $lens;
            $minLen = $lens[0];
            $maxLen = $lens[count($lens) - 1];
        } else {
            if (!self::isPosInt($minLen) || !self::isPosInt($maxLen)) return null;
            if ($maxLen < $minLen) return null;
            if ($maxLen >= 2 * $minLen) return null;
            $minLen = max($minLen, $nCheck + 1);
            for ($L = $minLen; $L <= $maxLen; $L++) $LENS[] = $L;
        }

        $KEEP = $ALPHA . (isset($cfg['keepChars']) ? (string) $cfg['keepChars'] : '');
        if ($checkMode) {
            $CA = self::checkAlphabet($algo);
            for ($i = 0; $i < strlen($CA); $i++) {
                if (strpos($KEEP, $CA[$i]) === false) $KEEP .= $CA[$i];
            }
        }
        if ($pattern !== null) {
            $pat = (string) $pattern; $meta = '\\^$.|?*+()[]{}';
            for ($i = 0; $i < strlen($pat); $i++) {
                $pc = $pat[$i];
                if ($pc === '\\') {
                    $i++;
                    if ($i < strlen($pat)) {
                        $pc = $pat[$i];
                        if (strpos($meta, $pc) !== false && strpos($KEEP, $pc) === false) $KEEP .= $pc;
                    }
                    continue;
                }
                if (strpos($meta, $pc) === false && !preg_match('/[A-Za-z0-9]/', $pc) && strpos($KEEP, $pc) === false) {
                    $KEEP .= $pc;
                }
            }
        }

        return [
            'algo' => $algo, 'source' => $source, 'strip' => $strip,
            'checkMode' => $checkMode, 'regexOnly' => $regexOnly, 'nCheck' => $nCheck,
            'minLen' => $minLen, 'maxLen' => $maxLen, 'LENS' => $LENS, 'KEEP' => $KEEP, 're' => $re,
        ];
    }

    private static function pooledVerifies(array $st, $t)
    {
        if ($st['re'] !== null && !self::patTest($st['re'], $t)) return false;
        if ($st['regexOnly']) return true;
        return self::validateId($st['algo'], $st['source'], $st['strip'], $t);
    }

    private static function pooledBetter(array $a, array $b)
    {
        if ($a['tok'] !== $b['tok']) return $a['tok'] > $b['tok'];
        if ($a['runs'] !== $b['runs']) return $a['runs'] < $b['runs'];
        if ($a['maxL'] !== $b['maxL']) return $a['maxL'] < $b['maxL'];
        return $a['chars'] > $b['chars'];
    }

    private static function pooledSegments(array $st, $raw)
    {
        $s = self::normalize($raw, '', true, true, $st['KEEP']); // clean(): keep only KEEP chars
        $N = strlen($s);
        $LENS = $st['LENS'];
        $sc = array_fill(0, $N + 1, null);
        $sc[$N] = ['tok' => 0, 'maxL' => 0, 'runs' => 0, 'chars' => 0, 'startsJunk' => false, 'move' => -1];
        for ($i = $N - 1; $i >= 0; $i--) {
            $c = $sc[$i + 1];
            $best = [
                'tok' => $c['tok'], 'maxL' => $c['maxL'],
                'runs' => $c['runs'] + ($c['startsJunk'] ? 0 : 1),
                'chars' => $c['chars'] + 1, 'startsJunk' => true, 'move' => 0,
            ];
            foreach ($LENS as $L) {
                if ($L > $N - $i) break;
                if (!self::pooledVerifies($st, substr($s, $i, $L))) continue;
                $ch = $sc[$i + $L];
                $cand = [
                    'tok' => $ch['tok'] + 1, 'maxL' => ($L > $ch['maxL'] ? $L : $ch['maxL']),
                    'runs' => $ch['runs'], 'chars' => $ch['chars'], 'startsJunk' => false, 'move' => $L,
                ];
                if (self::pooledBetter($cand, $best)) $best = $cand;
            }
            $sc[$i] = $best;
        }
        $segs = []; $pos = 0; $junk = '';
        while ($pos < $N) {
            $m = $sc[$pos]['move'];
            if ($m > 0) {
                if ($junk !== '') { $segs[] = ['type' => 'junk', 'text' => $junk]; $junk = ''; }
                $segs[] = ['type' => 'id', 'id' => substr($s, $pos, $m), 'valid' => true];
                $pos += $m;
            } else {
                $junk .= $s[$pos]; $pos++;
            }
        }
        if ($junk !== '') $segs[] = ['type' => 'junk', 'text' => $junk];

        // re-scan junk for well-formed-but-wrong-check members (check + pattern only)
        if ($st['re'] !== null && $st['checkMode']) {
            $out = [];
            foreach ($segs as $seg) {
                if ($seg['type'] !== 'junk') { $out[] = $seg; continue; }
                $rest = $seg['text']; $buf = '';
                while (strlen($rest)) {
                    $hit = '';
                    $lim2 = min($st['maxLen'], strlen($rest));
                    for ($L2 = $st['minLen']; $L2 <= $lim2 && $hit === ''; $L2++) {
                        if (self::patTest($st['re'], substr($rest, 0, $L2))) $hit = substr($rest, 0, $L2);
                    }
                    if ($hit !== '') {
                        if ($buf !== '') { $out[] = ['type' => 'junk', 'text' => $buf]; $buf = ''; }
                        $out[] = ['type' => 'id', 'id' => $hit, 'valid' => false];
                        $rest = substr($rest, strlen($hit));
                    } else {
                        $buf .= $rest[0]; $rest = substr($rest, 1);
                    }
                }
                if ($buf !== '') $out[] = ['type' => 'junk', 'text' => $buf];
            }
            $segs = $out;
        }
        return $segs;
    }

    /**
     * Segment a pooled field into members + junk. Returns a list of
     *   ['type'=>'id','id'=>..,'valid'=>bool]  or  ['type'=>'junk','text'=>..]
     * or null when the config is unsafe (client shows a config error instead).
     */
    public static function pooledParse(array $cfg, $raw)
    {
        $st = self::pooledState($cfg);
        if ($st === null) return null;
        self::$pooledPcreError = false;
        $segs = self::pooledSegments($st, (string) $raw);
        // A PCRE engine failure during segmentation makes the result untrustworthy;
        // treat the field as unconfigurable (no verdict) rather than log a false one.
        return self::$pooledPcreError ? null : $segs;
    }

    /** Server-side pooled verdict mirroring the browser render() problem checks. */
    public static function validatePooledField(array $cfg, $raw)
    {
        $segs = self::pooledParse($cfg, $raw);
        if ($segs === null) return ['ok' => true, 'reason' => 'unconfigurable', 'count' => 0];
        $ids = 0; $junk = 0; $bad = 0; $dups = 0; $seen = [];
        foreach ($segs as $seg) {
            if ($seg['type'] === 'id') {
                $ids++;
                if (!$seg['valid']) $bad++;
                if (isset($seen[$seg['id']])) $dups++;
                $seen[$seg['id']] = true;
            } else {
                $junk++;
            }
        }
        $problems = [];
        if (!$ids) $problems[] = 'no-id';
        if ($bad)  $problems[] = 'check-character';
        if ($junk) $problems[] = 'junk';
        if ($dups) $problems[] = 'duplicate';
        $expected = (isset($cfg['expectedIds']) && $cfg['expectedIds']) ? (int) $cfg['expectedIds'] : null;
        if ($expected && $ids !== $expected) $problems[] = 'count';
        return ['ok' => count($problems) === 0, 'reason' => implode(';', $problems), 'count' => $ids];
    }

    // -- engines ------------------------------------------------------------

    private static function idx($alphabet, $ch)
    {
        $i = strpos($alphabet, $ch);
        if ($i === false) {
            throw new \InvalidArgumentException("character '$ch' not in alphabet");
        }
        return $i;
    }

    /** ISO/IEC 7064 pure systems: p = ((p + d) * r) mod M. */
    private static function pure($payload, $alphabet, $M, $r, $n, $checkAlphabet)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $p = 0;
        foreach (str_split($payload) as $ch) {
            $d = self::idx($alphabet, $ch);
            $p = (($p + $d) * $r) % $M;
        }
        for ($k = 0; $k < $n - 1; $k++) {
            $p = ($p * $r) % $M;
        }
        if ($n === 1) {
            $cv = ((1 - $p) % $M + $M) % $M;
            return $checkAlphabet[$cv];
        }
        // Multi-char (Mod 97-10): check value in [2, M+1], NOT reduced mod M;
        // emit n radix-r digits, high digit first, via the payload alphabet.
        $cv = ($M + 1) - $p;
        $digits = [];
        $x = $cv;
        for ($k = 0; $k < $n; $k++) {
            $digits[] = $alphabet[$x % $r];
            $x = intdiv($x, $r);
        }
        return implode('', array_reverse($digits));
    }

    /** ISO/IEC 7064 hybrid systems (Mod n+1,n over the alphabet). */
    private static function hybrid($payload, $alphabet)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $modulus = strlen($alphabet);
        $check = intdiv($modulus, 2);
        foreach (str_split($payload) as $ch) {
            $d = self::idx($alphabet, $ch);
            $check = ((($check ?: $modulus) * 2) % ($modulus + 1) + $d) % $modulus;
        }
        $v = ((1 - (($check ?: $modulus) * 2) % ($modulus + 1)) % $modulus + $modulus) % $modulus;
        return $alphabet[$v];
    }

    /** Hybrid recurrence over pre-mapped values -> check value in [0, modulus). */
    private static function hybridValue($values, $modulus)
    {
        $check = intdiv($modulus, 2);
        foreach ($values as $d) {
            $check = ((($check ?: $modulus) * 2) % ($modulus + 1) + $d) % $modulus;
        }
        return ((1 - (($check ?: $modulus) * 2) % ($modulus + 1)) % $modulus + $modulus) % $modulus;
    }

    /** Letters-only variant 1: fold 36 symbols onto 26 letters, one letter out. */
    private static function letters1($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $vals = [];
        foreach (str_split($payload) as $ch) {
            $vals[] = self::idx(self::ALNUM36, $ch) % 26;
        }
        $v = self::hybridValue($vals, 26);
        $A = self::LETTERS26;
        return $A[$v];
    }

    /** Letters-only variant 2: full Mod 37,36 value as two base-6 letters (A-F). */
    private static function letters2($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $vals = [];
        foreach (str_split($payload) as $ch) {
            $vals[] = self::idx(self::ALNUM36, $ch);
        }
        $v = self::hybridValue($vals, 36);
        $L = 'ABCDEF';
        return $L[intdiv($v, 6)] . $L[$v % 6];
    }

    private static function damm($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        static $T = [
            [0, 3, 1, 7, 5, 9, 8, 6, 4, 2],
            [7, 0, 9, 2, 1, 5, 4, 8, 6, 3],
            [4, 2, 0, 6, 8, 7, 1, 3, 5, 9],
            [1, 7, 5, 0, 9, 8, 3, 4, 2, 6],
            [6, 1, 2, 3, 0, 4, 5, 9, 7, 8],
            [3, 6, 7, 4, 2, 0, 9, 5, 8, 1],
            [5, 8, 6, 9, 7, 2, 0, 1, 3, 4],
            [8, 9, 4, 5, 3, 6, 2, 0, 1, 7],
            [9, 4, 3, 8, 6, 1, 7, 2, 0, 5],
            [2, 5, 8, 1, 4, 3, 6, 7, 9, 0],
        ];
        $interim = 0;
        foreach (str_split($payload) as $ch) {
            $d = self::idx(self::DIGITS, $ch);
            $interim = $T[$interim][$d];
        }
        return (string) $interim;
    }

    private static function verhoeff($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $D = self::verhoeffD();
        $P = self::powerPerm();
        $INV = [0, 4, 3, 2, 1, 5, 6, 7, 8, 9];
        $c = 0;
        foreach (array_reverse(str_split($payload)) as $i => $ch) {
            $d = self::idx(self::DIGITS, $ch);
            $c = $D[$c][$P[($i + 1) % 8][$d]];
        }
        return (string) $INV[$c];
    }

    private static function luhn($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $total = 0;
        foreach (array_reverse(str_split($payload)) as $idx => $ch) {
            $d = self::idx(self::DIGITS, $ch);
            if ($idx % 2 === 0) {
                $d *= 2;
                if ($d > 9) $d -= 9;
            }
            $total += $d;
        }
        return (string) ((10 - ($total % 10)) % 10);
    }

    /** Verhoeff D5 multiplication table. */
    private static function verhoeffD()
    {
        return [
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
            [1, 2, 3, 4, 0, 6, 7, 8, 9, 5],
            [2, 3, 4, 0, 1, 7, 8, 9, 5, 6],
            [3, 4, 0, 1, 2, 8, 9, 5, 6, 7],
            [4, 0, 1, 2, 3, 9, 5, 6, 7, 8],
            [5, 9, 8, 7, 6, 0, 4, 3, 2, 1],
            [6, 5, 9, 8, 7, 1, 0, 4, 3, 2],
            [7, 6, 5, 9, 8, 2, 1, 0, 4, 3],
            [8, 7, 6, 5, 9, 3, 2, 1, 0, 4],
            [9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
        ];
    }

    /** Verhoeff permutation family as successive powers of the base permutation. */
    private static function powerPerm()
    {
        $base = [1, 5, 7, 6, 2, 8, 3, 0, 9, 4];
        $table = [range(0, 9)];
        for ($k = 1; $k < 8; $k++) {
            $prev = $table[$k - 1];
            $row = [];
            for ($x = 0; $x < 10; $x++) {
                $row[] = $base[$prev[$x]];
            }
            $table[] = $row;
        }
        return $table;
    }
}
