<?php
/**
 * CheckCharacter — faithful PHP port of the check-character engine.
 *
 * Ported line-for-line from the source of truth
 *   qrcode_generation/check_characters.py
 * in the qrcode_generation repository. Correctness is proven, not asserted:
 * tests/parity_php.php recomputes every row of tests/check_fixture.json (the
 * fixture generated by the Python engine) and fails on any mismatch. That makes
 * PHP a verified fourth runtime alongside Python, JavaScript, and Excel/VBA.
 *
 * Used by the module's server-side guard (redcap_save_record) so an invalid ID
 * is caught even when it arrives via the API or data import, where client-side
 * JavaScript never runs.
 */

namespace INSPIRE\UniversalValidator;

class CheckCharacter
{
    const DIGITS    = '0123456789';
    const LETTERS26 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const ALNUM36   = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';

    // Named weighted-modulus schemes — a byte-for-byte copy of WEIGHTED_SCHEMES
    // in the Python source of truth (qrcode_generation/check_characters.py) and
    // the JS engine (js/engine.js). Adding a scheme is one row here plus the same
    // row in those two ports; nothing else in this file changes. All emit one
    // check character over a digit payload.
    const WEIGHTED_SCHEMES = [
        'gs1_mod10'      => ['modulus' => 10, 'mode' => 'cycle',  'weights' => [3, 1],
                             'from' => 'right', 'complement' => true,  'checkAlphabet' => self::DIGITS],
        'aba_mod10'      => ['modulus' => 10, 'mode' => 'cycle',  'weights' => [3, 7, 1],
                             'from' => 'left',  'complement' => true,  'checkAlphabet' => self::DIGITS],
        'mrz_mod10'      => ['modulus' => 10, 'mode' => 'cycle',  'weights' => [7, 3, 1],
                             'from' => 'left',  'complement' => false, 'checkAlphabet' => self::DIGITS],
        'weighted_mod11' => ['modulus' => 11, 'mode' => 'linear', 'start' => 2, 'step' => 1,
                             'from' => 'right', 'complement' => true,  'checkAlphabet' => self::DIGITS . 'X'],
    ];

    // Hard caps that bound the pooled parser's work per keystroke (client) and
    // per save (server). A rule beyond them is a config error at settings-save
    // time and "unconfigurable" at runtime — never silently expensive. The JS
    // engine mirrors these as literals (js/engine.js, QRID_MAX_* block); keep
    // the two in sync.
    const MAX_ID_LEN      = 64;   // longest single ID/member the parser will consider
    const MAX_LEN_CHOICES = 32;   // most candidate lengths a pooled rule may declare
    const MAX_ALTERNATES  = 8;    // most ID formats one rule may accept
    const MAX_ALT_LABEL   = 40;   // an alternate's display name (reaches innerHTML)
    const MAX_EXPECTED_IDS = 9999;
    const MAX_KEEP_CHARS  = 64;
    const MAX_POOLED_LEN  = 4096; // absolute pooled scan cap (client QRID_MAX_POOLED_LEN)
    // One pooled parse costs about (scanned length) x |PAIRS| x (member length)
    // "char-ops"; this budget bounds the product for every legal config, so an
    // expensive rule shrinks its scan cap instead of stalling the save hook.
    //
    // The unit is nominal, not literal: one step is a substr, a regex test and
    // - whenever the pattern does not reject first - a full normalize + source
    // + check-character computation, around an order of magnitude above a
    // character comparison. Measured at each config's own cap, the old
    // 2,000,000 admitted ~300 ms per pooled field per save, paid again per
    // record by the durable scan. 500,000 leaves every ordinary rule at the
    // full 4096 and shrinks only the wide tail. Keep in sync with
    // QRID_POOLED_WORK_BUDGET (js).
    const POOLED_WORK_BUDGET = 500000;
    // Config-time bound on BOUNDED-quantifier backtracking (riskyPattern stage
    // two-b). A contiguous run of overlapping bounded repeats (A{1,20}A{1,20}…)
    // backtracks with the factor count as the exponent, so a long chain freezes a
    // browser's engine even though each factor is bounded and PCRE2 auto-
    // possessifies it — and the client has no match-time backstop the server's
    // preg_last_error guard provides. Refuse a run whose product of per-factor
    // match-length choices exceeds this. Chosen (measured) so the deliberate
    // 3-factor residue A{1,40}A{1,40}A{1,40}9 (= 64000) still passes and a browser-
    // freezing chain (≥5 factors of {1,20} = 3.2M) does not; the worst admitted
    // case measures ~40 ms. Keep in sync with QRID_MAX_BACKTRACK_PRODUCT (js).
    const MAX_BACKTRACK_PRODUCT = 1000000;

    /** Number of check characters an algorithm appends. */
    public static function nCheckChars($name)
    {
        if ($name === 'none') return 0;
        if ($name === 'iso7064_mod97_10' || $name === 'iso7064_letters2') return 2;
        return 1;
    }

    /**
     * Return ONLY the check character(s) for a prepared payload.
     * Mirrors CheckCharacterAlgorithm.compute in the Python engine.
     */
    public static function compute($name, $payload)
    {
        if (isset(self::WEIGHTED_SCHEMES[$name])) {
            return self::weighted($payload, self::WEIGHTED_SCHEMES[$name]);
        }
        switch ($name) {
            case 'iso7064_mod11_2':  return self::pure($payload, self::DIGITS,  11, 2, 1, self::DIGITS . 'X');
            case 'iso7064_mod37_2':  return self::pure($payload, self::ALNUM36, 37, 2, 1, self::ALNUM36 . '*');
            case 'iso7064_mod97_10': return self::pure($payload, self::DIGITS,  97, 10, 2, self::DIGITS);
            case 'iso7064_mod11_10': return self::hybrid($payload, self::DIGITS);
            case 'iso7064_mod37_36': return self::hybrid($payload, self::ALNUM36);
            case 'iso7064_letters1': return self::letters1($payload);
            case 'iso7064_letters2': return self::letters2($payload);
            case 'damm':             return self::damm($payload);
            case 'verhoeff':         return self::verhoeff($payload);
            case 'luhn':             return self::luhn($payload);
            case 'none':             return '';
            default:
                throw new \InvalidArgumentException("unknown check algorithm: $name");
        }
    }

    // -- normalization + source extraction (mirror check_characters.py) ------

    /**
     * Unicode dash folding + uppercase + delimiter strip.
     *
     * Multibyte-safe throughout so the server verdict matches the browser
     * engine (js/engine.js), which normalizes with Unicode-aware primitives
     * (String.toUpperCase, Array.from, /\p{Nd}/u). Uses mb_strtoupper for case
     * folding and code-point splitting for strip/keep_only so a non-ASCII
     * character is never mangled into raw bytes.
     */
    public static function normalize($value, $strip = "-/ _|\\", $uppercase = true, $unifyDashes = true, $keepOnly = null)
    {
        $s = (string) $value;
        if ($unifyDashes) {
            $s = str_replace(
                ["\u{2010}", "\u{2011}", "\u{2012}", "\u{2013}", "\u{2014}", "\u{2015}", "\u{2212}"],
                '-',
                $s
            );
        }
        if ($uppercase) {
            $s = mb_strtoupper($s, 'UTF-8');
        }
        if ($strip !== null && $strip !== '') {
            // Split the strip set by code point (not byte) so a multibyte
            // delimiter is removed as a whole character, never byte-by-byte.
            $stripChars = preg_split('//u', $strip, -1, PREG_SPLIT_NO_EMPTY);
            if ($stripChars) $s = str_replace($stripChars, '', $s);
        }
        if ($keepOnly !== null) {
            $keep = array_flip(preg_split('//u', $keepOnly, -1, PREG_SPLIT_NO_EMPTY) ?: []);
            $out = '';
            foreach (preg_split('//u', $s, -1, PREG_SPLIT_NO_EMPTY) ?: [] as $ch) {
                if (isset($keep[$ch])) $out .= $ch;
            }
            $s = $out;
        }
        return $s;
    }

    /**
     * Extract the substring the algorithm runs over.
     *
     * Unicode-aware (\p{Nd}) to mirror the browser engine: a non-ASCII decimal
     * digit is KEPT here, then rejected downstream by the ASCII algorithm
     * alphabet — exactly as the JS side behaves. ASCII \d/\D would silently
     * strip such a character and flip the verdict, breaking client/server parity.
     */
    public static function applySource($norm, $source)
    {
        if ($source === 'digits_only')   return preg_replace('/[^\p{Nd}]/u', '', $norm);
        if ($source === 'sequence_only') return preg_match('/(\p{Nd}+)\P{Nd}*$/u', $norm, $m) ? $m[1] : '';
        return $norm; // normalized_id (default)
    }

    /**
     * Validate a full (check-bearing) ID: normalize, peel the check character(s),
     * apply the source to the remainder, recompute and compare. Returns true for
     * the "none" algorithm (no check character to verify).
     */
    public static function validateId($algo, $source, $strip, $fullRaw)
    {
        if ($algo === 'none') return true;
        try {
            $norm = self::normalize($fullRaw, $strip);
            $n = self::nCheckChars($algo);
            if ($n <= 0) return true;
            // Code-point (not byte) length/slicing so peeling the check
            // character(s) matches the browser engine on multibyte input.
            $len = mb_strlen($norm, 'UTF-8');
            if ($len <= $n) return false;
            $body  = mb_substr($norm, 0, $len - $n, 'UTF-8');
            $check = mb_substr($norm, $len - $n, null, 'UTF-8');
            $payload = self::applySource($body, $source);
            if ($payload === '') return false;
            return self::compute($algo, $payload) === $check;
        } catch (\Throwable $e) {
            return false; // out-of-alphabet character etc. -> not valid
        }
    }

    /**
     * Mint an ID: append the computed check character(s) to the RAW value.
     * Mirrors the browser engine's appendCheck (QRCheck.appendCheck): the check
     * is computed over the normalized payload but appended to the raw string so
     * any separators the user typed are preserved. When placement is
     * "append_after_delimiter" the check is separated from the body by $delimiter,
     * exactly as the JS side does. Used by the parity harness to verify the
     * append/validate scheme operations, not by the runtime guard.
     */
    public static function appendCheck($algo, $source, $strip, $raw, $placement = 'append', $delimiter = '-')
    {
        if ($algo === 'none') return (string) $raw;
        $norm = self::normalize($raw, $strip);
        $payload = self::applySource($norm, $source);
        if ($payload === '') {
            throw new \InvalidArgumentException('ID normalizes to empty; nothing to compute a check over');
        }
        $chk = self::compute($algo, $payload);
        if ($chk === '') return (string) $raw;
        if ($placement === 'append_after_delimiter') return (string) $raw . $delimiter . $chk;
        return (string) $raw . $chk;
    }

    // -- server-side rule validation (mirror the browser rule semantics) -----

    /** The check alphabet an algorithm emits into (mirrors the JS registry). */
    /**
     * Is $name an algorithm this engine implements? Derived from checkAlphabet
     * (which answers '' for anything unknown) so there is no second list to
     * keep in step with compute(). "none" counts as known: it means format-only.
     */
    public static function knownAlgorithm($name)
    {
        return $name === 'none' || self::checkAlphabet($name) !== '';
    }

    public static function checkAlphabet($name)
    {
        if (isset(self::WEIGHTED_SCHEMES[$name])) {
            return self::WEIGHTED_SCHEMES[$name]['checkAlphabet'];
        }
        switch ($name) {
            case 'iso7064_mod11_2':  return self::DIGITS . 'X';
            case 'iso7064_mod37_2':  return self::ALNUM36 . '*';
            case 'iso7064_mod97_10': return self::DIGITS;
            case 'iso7064_mod11_10': return self::DIGITS;
            case 'iso7064_mod37_36': return self::ALNUM36;
            case 'iso7064_letters1': return self::LETTERS26;
            case 'iso7064_letters2': return 'ABCDEF';
            case 'damm':             return self::DIGITS;
            case 'verhoeff':         return self::DIGITS;
            case 'luhn':             return self::DIGITS;
            default:                 return '';
        }
    }

    /**
     * Conservative catastrophic-backtracking detector — the PHP twin of the
     * browser's QRID_riskyPattern (js/engine.js). Two stages, both at config
     * time. Stage one rejects the EXPONENTIAL shapes: nested quantifiers AND any
     * repetition of a group that can match the same text more than one way
     * (alternation, optionals, or inner quantifiers) — (a|aa)+, (a?)+ and
     * ((a)|(aa))+ are refused, not only (a+)+ — collapsing inner groups layer by
     * layer so nesting cannot hide the shape. Stage two (polynomialOverlap)
     * rejects the POLYNOMIAL shapes stage one misses: two or more unbounded
     * quantifiers over overlapping character classes with no mandatory separator
     * between them (.*.*, [0-9]*[0-9]*, [A-Z]+[A-Z0-9]+). Those do not blow up on
     * PCRE2 (it auto-possessifies) but freeze a browser's backtracking engine,
     * so the client needs them refused before they are ever run. Genuinely
     * linear shapes — disjoint adjacent classes ([A-Z]+[0-9]+) and a mandatory
     * separator (.*x.*) — are admitted. Still a heuristic, not a safety proof: it
     * over-rejects, and the match-time PCRE-error guard remains the server
     * backstop for the bounded residue (e.g. A{1,40}A{1,40}A{1,40}9). Keep in
     * exact sync with the JS version; tests/risky_php.php and tests/risky_js.cjs
     * assert the two agree on a shared pattern list.
     */
    public static function riskyPattern($src)
    {
        if (mb_strlen((string) $src, 'UTF-8') > 512) return true;           // absurd pattern source
        $s = preg_replace('/\\\\./', '', (string) $src);                    // ignore escaped chars
        $s = preg_replace('/\(\?(<?[=!]|:)/', '(', $s);                     // (?: (?= (?! (?<= (?<! -> plain (
        // Whitespace is an explicit ASCII class, NOT \s: PCRE \s (no /u) and JS \s
        // classify Unicode whitespace differently, which would diverge. Bounded
        // quantifiers ({n,m}/{n,}) count as the "repeating" token so nested bounded
        // quantifiers are caught too. Keep BYTE-IDENTICAL to QRID_riskyPattern (js).
        for (;;) {
            if (preg_match('/[+*][ \t\n\r\f]*[*+{]/', $s)) return true;                                        // a++  a*+  a*{2} ...
            if (preg_match('/\([^()]*(?:[*+]|\{[0-9]+,[0-9]*\})[^()]*\)[ \t\n\r\f]*[*+{?]/', $s)) return true; // (…a+…)+  (…{1,20}…){1,20}
            if (preg_match('/\[[^\]]*\][ \t\n\r\f]*[*+][ \t\n\r\f]*[*+{]/', $s)) return true;                  // [0-9]+* style
            // Collapse every innermost group: a body that can match more than one
            // way (alternation, optional, variable-length content) becomes a
            // variable-length token X*; a fixed body becomes the single token A.
            // A repetition of a variable token is then caught by the rules above
            // on the next pass — (a|aa)+ -> X*+ -> rule 1.
            $t = preg_replace_callback('/\(([^()]*)\)/', function ($m) {
                return (preg_match('/[|?*+]/', $m[1]) || preg_match('/\{[0-9]+,[0-9]*\}/', $m[1])) ? 'X*' : 'A';
            }, $s);
            if ($t === $s) break;
            $s = $t;
        }
        // Stage two: the polynomial-overlap class the exponential rules miss.
        if (self::polynomialOverlap($s)) return true;   // .*.*  [0-9]*[0-9]*  [A-Z]+[A-Z0-9]+
        return false;
    }

    /**
     * Reject two or more unbounded quantifiers (*, +, {n,}) whose atoms have
     * overlapping character sets with no mandatory atom pinning a split between
     * them — the polynomial-backtracking class stage one lets through. Operates
     * on $s AFTER escape-stripping, lookaround-unwrapping, and the group-collapse
     * loop above (so groups are already reduced to A / X* tokens; two repeats of
     * the same collapsed group therefore read as overlapping too). Assumes an
     * ASCII pattern source, which the server match path enforces elsewhere. Keep
     * behavior in sync with QRID_polyOverlap (js).
     */
    private static function polynomialOverlap($s)
    {
        $toks = self::tokenizePattern($s);
        $m = count($toks);
        for ($i = 0; $i < $m; $i++) {
            if (!$toks[$i]['unbounded']) continue;
            for ($j = $i + 1; $j < $m; $j++) {
                if ($toks[$j]['unbounded'] && self::classesOverlap($toks[$i]['cls'], $toks[$j]['cls'])) {
                    return true;
                }
                if ($toks[$j]['mandatory']) break;   // a must-match atom anchors the split point
            }
        }
        // Stage two-b: the BOUNDED-quantifier chain (F1). A contiguous run of
        // overlapping bounded repeats (A{1,20}A{1,20}…) backtracks with the factor
        // count as the exponent — bounded per factor, but still a browser tab
        // freeze past ~5 factors, and the client has no match-time guard. Bound
        // the product of per-factor match-length choices; a fixed atom (choices 1),
        // an unbounded quantifier, or a disjoint class ends the run and anchors a
        // split. A single quantifier (or the deliberate 3-factor residue) stays
        // under the budget. Twin of QRID_polyOverlap stage two-b (js).
        // F1-1 fix: only a genuine split point ends a run — an UNBOUNDED quantifier
        // (stage two-a's territory) or a class DISJOINT from the run so far. A
        // fixed/bare atom whose class OVERLAPS does NOT end the run (its char is
        // fungible with the surrounding class, so it cannot pin a split — a lone
        // [0-9] between {1,20} digit runs must not reset the product); it bridges on
        // with choices 1. Track the class FORWARD so a bridging chain is whole.
        for ($a = 0; $a < $m; $a++) {
            if ($toks[$a]['choices'] < 2) continue;                                      // a run starts at a bounded repeat
            $prod = $toks[$a]['choices'];
            $prevCls = $toks[$a]['cls'];
            for ($b = $a + 1; $b < $m; $b++) {
                if ($toks[$b]['unbounded']) break;                                       // unbounded -> stage two-a; ends the bounded run
                if (!self::classesOverlap($prevCls, $toks[$b]['cls'])) break;            // a DISJOINT atom pins a split, ending the run
                if ($toks[$b]['choices'] >= 2) {
                    $prod *= $toks[$b]['choices'];
                    if ($prod > self::MAX_BACKTRACK_PRODUCT) return true;
                }
                $prevCls = $toks[$b]['cls'];                                             // overlapping fixed atom bridges on (does not pin)
            }
        }
        return false;
    }

    /**
     * Split a normalized pattern into atoms, each carrying its character set and
     * quantifier facts. cls === null means "universal" (a '.', or a collapsed
     * group token whose contents are unknown — treated as overlapping everything,
     * conservatively). unbounded = the quantifier has no upper limit (*, +, {n,}).
     * mandatory = it must consume at least one character (bare atom, +, {n>=1}).
     */
    private static function tokenizePattern($s)
    {
        $toks = [];
        $n = strlen($s);
        $i = 0;
        while ($i < $n) {
            $c = $s[$i];
            $cls = null;
            if ($c === '.') { $cls = null; $i++; }
            elseif ($c === '[') {
                $close = strpos($s, ']', $i + 1);
                if ($close === false) { $i++; continue; }   // unterminated class: skip the '['
                $cls = self::expandClass(substr($s, $i + 1, $close - $i - 1));
                $i = $close + 1;
            }
            elseif (strpos('^$*+?{}|()', $c) !== false) { $i++; continue; }   // anchors / stray metachars: not atoms
            else { $cls = $c; $i++; }                                          // a literal char (incl. A / X collapse tokens)
            // read the quantifier that follows this atom. `choices` = the number
            // of distinct match-lengths the atom can take (its backtracking slack):
            // 1 for a bare atom or a fixed {n}, 2 for ?, (hi-lo+1) for {lo,hi};
            // an unbounded quantifier is handled by stage two-a, not the product.
            $unbounded = false; $mandatory = true; $choices = 1;   // a bare atom must match once
            if ($i < $n) {
                $q = $s[$i];
                if ($q === '*') { $unbounded = true; $mandatory = false; $i++; }
                elseif ($q === '+') { $unbounded = true; $mandatory = true; $i++; }
                elseif ($q === '?') { $unbounded = false; $mandatory = false; $choices = 2; $i++; }
                elseif ($q === '{') {
                    $close = strpos($s, '}', $i + 1);
                    if ($close !== false && preg_match('/^([0-9]*)(,?)([0-9]*)$/', substr($s, $i + 1, $close - $i - 1), $mm)) {
                        $lo = $mm[1] === '' ? 0 : (int) $mm[1];
                        $unbounded = ($mm[2] === ',') && ($mm[3] === '');   // {n,} unbounded; {n} / {n,m} bounded
                        $mandatory = $lo >= 1;
                        if (!$unbounded) {
                            $hi = ($mm[3] === '') ? $lo : (int) $mm[3];      // {n} -> hi=lo (choices 1)
                            $choices = $hi - $lo + 1;
                            if ($choices < 1) $choices = 1;                  // malformed {5,2}: PCRE rejects it anyway
                        }
                        $i = $close + 1;
                    }
                }
            }
            $toks[] = ['cls' => $cls, 'unbounded' => $unbounded, 'mandatory' => $mandatory, 'choices' => $choices];
        }
        return $toks;
    }

    /** Expand a bracket-class body to its literal ASCII members; null = universal. */
    private static function expandClass($inner)
    {
        if ($inner === '') return '';                // matches nothing
        if ($inner[0] === '^') return null;          // negated class: large -> universal
        $out = '';
        $len = strlen($inner);
        $k = 0;
        while ($k < $len) {
            if ($k + 2 < $len && $inner[$k + 1] === '-') {
                $lo = ord($inner[$k]); $hi = ord($inner[$k + 2]);
                if ($lo <= $hi && $hi - $lo <= 255) {
                    for ($x = $lo; $x <= $hi; $x++) $out .= chr($x);
                    $k += 3; continue;
                }
            }
            $out .= $inner[$k]; $k++;
        }
        return $out;
    }

    /** Do two character sets share a member? null = universal (overlaps all). */
    private static function classesOverlap($a, $b)
    {
        if ($a === null || $b === null) return true;
        if ($a === '' || $b === '') return false;
        $len = strlen($a);
        for ($k = 0; $k < $len; $k++) {
            if (strpos($b, $a[$k]) !== false) return true;
        }
        return false;
    }

    /**
     * Test a value against a project ID regex (JavaScript-authored, anchored).
     * The value is normalized the way the browser tests format — uppercase +
     * unified dashes, separators KEPT. Returns true (i.e. "do not raise a format
     * error the client would not") when the pattern is catastrophic, when the
     * regex cannot be compiled server-side (JS/PCRE dialect gap), or when the PCRE
     * engine itself fails at match time (backtrack/recursion limit) — a PCRE
     * failure is not a real format mismatch and must never be logged as one.
     */
    public static function matchesPattern($value, $pattern)
    {
        if ($pattern === null || $pattern === '') return true;
        if (self::riskyPattern($pattern)) return true;      // never run a catastrophic pattern
        $norm = trim(self::normalize($value, '', true, true, null));
        // JS RegExp (UTF-16 code units) and PCRE /u (code points) count a
        // non-ASCII character differently — e.g. an astral emoji is two units
        // to the browser and one to PCRE, so "." patterns flip verdicts. The
        // proven parity subset is printable ASCII; outside it the server must
        // fail OPEN (no format log) rather than risk logging a mismatch the
        // client never showed (COR-004).
        if (preg_match('/[^\x20-\x7E]/', $norm)) return true;
        $body = preg_replace('/^\^/', '', (string) $pattern);
        $body = preg_replace('/\$$/', '', $body);
        $re = self::compilePattern($body);
        if ($re === null) return true;
        $m = @preg_match($re, $norm);
        if ($m === false || preg_last_error() !== PREG_NO_ERROR) return true; // engine error, not a format miss
        return $m === 1;
    }

    /**
     * Every rule is a LIST of accepted ID formats, each with its own pattern and
     * its own check algorithm (or "none"). A rule written the old way — one
     * scalar algorithm, one scalar idPattern — normalizes to a ONE-ELEMENT list,
     * so every consumer runs exactly one loop and there is no second code path.
     *
     * Pure normalization: total, no gates, no compilation. The gates belong to
     * the caller, because the three consumers have three different failure
     * policies — validateSingleField fails OPEN, pooledState fails CLOSED, and
     * AnnotationRules::checkFragment words an error. Conflating them would break
     * whichever one it did not match.
     *
     * 'lengths' is null when the alternate does not declare its own; pooledState
     * then hands it the rule-level set, which is what makes a legacy rule
     * byte-identical to today. Returns null when the shape is unusable.
     *
     * Twin of QRID_alternatesOf (js).
     */
    public static function alternatesOf(array $cfg)
    {
        $algo   = (isset($cfg['algorithm']) && $cfg['algorithm'] !== '') ? $cfg['algorithm'] : 'iso7064_mod37_36';
        $source = (isset($cfg['source']) && $cfg['source'] !== '') ? $cfg['source'] : 'normalized_id';
        $strip  = (array_key_exists('strip', $cfg) && $cfg['strip'] !== null) ? $cfg['strip'] : '';

        if (!isset($cfg['alternates']) || $cfg['alternates'] === null || $cfg['alternates'] === '') {
            $pattern = (isset($cfg['idPattern']) && $cfg['idPattern'] !== '') ? $cfg['idPattern'] : null;
            return [[
                'label' => '', 'pattern' => $pattern, 'algorithm' => $algo,
                'source' => $source, 'strip' => $strip, 'lengths' => null,
            ]];
        }
        $raw = $cfg['alternates'];
        // A JSON object would order its keys differently in the two runtimes
        // (PHP keeps insertion order, JS reorders integer-like keys), so only a
        // list is accepted. array_is_list is 8.1+, hence the manual test.
        if (!is_array($raw) || !count($raw) || array_keys($raw) !== range(0, count($raw) - 1)) return null;
        if (count($raw) > self::MAX_ALTERNATES) return null;
        $out = [];
        foreach ($raw as $a) {
            if (!is_array($a)) return null;
            if (!isset($a['pattern']) || !is_string($a['pattern']) || $a['pattern'] === '') return null;
            $label = (isset($a['label']) && $a['label'] !== null) ? (string) $a['label'] : '';
            if (strlen($label) > self::MAX_ALT_LABEL || preg_match('/[^\x20-\x7E]/', $label)) return null;
            $lens = null;
            if (isset($a['lengths']) && $a['lengths'] !== null) {
                if (!is_array($a['lengths']) || !count($a['lengths'])) return null;
                foreach ($a['lengths'] as $L) if (!self::isPosInt($L)) return null;
                $lens = array_values(array_unique(array_map('intval', $a['lengths'])));
                sort($lens);
            }
            $out[] = [
                'label'     => $label,
                'pattern'   => $a['pattern'],
                'algorithm' => (isset($a['algorithm']) && $a['algorithm'] !== '') ? $a['algorithm'] : $algo,
                'source'    => (isset($a['source']) && $a['source'] !== '') ? $a['source'] : $source,
                'strip'     => (array_key_exists('strip', $a) && $a['strip'] !== null) ? $a['strip'] : $strip,
                'lengths'   => $lens,
            ];
        }
        return $out;
    }

    /**
     * Can any declared member length be built by adding TWO OR MORE of the
     * declared lengths together? If so one token can span several real members
     * and still verify, so a mis-scan is reported as a clean ID — the failure
     * the pooled parser's structural guarantee exists to make impossible.
     *
     * Returns null when the set is safe, else ['target' => L, 'parts' => [...]]
     * naming one witness decomposition.
     *
     * Supersedes the pairwise test this replaces, which only ever compared TWO
     * lengths and so accepted [4,12] even though 12 = 4+4+4. Unbounded-coin
     * reachability, O(maxLen x |U|). Twin of QRID_swallowSum (js) — keep the
     * witness identical, because both runtimes print it.
     *
     * $lens must already be deduped, integer-normalised and sorted ascending.
     */
    public static function swallowSum(array $lens)
    {
        if (!count($lens)) return null;
        $maxL = $lens[count($lens) - 1];
        // rep1[s] = s is the sum of ONE OR MORE declared lengths; via[s] = a
        // length used in that sum, so a witness can be reconstructed.
        $rep1 = array_fill(0, $maxL + 1, false);
        $via  = array_fill(0, $maxL + 1, 0);
        for ($s = 1; $s <= $maxL; $s++) {
            foreach ($lens as $L) {
                if ($L > $s) break;                 // ascending
                if ($L === $s || $rep1[$s - $L]) { $rep1[$s] = true; $via[$s] = $L; break; }
            }
        }
        // L is a sum of >= 2 lengths iff some SHORTER declared length leaves a
        // remainder that is itself a sum of one or more.
        foreach ($lens as $L) {
            foreach ($lens as $first) {
                if ($first >= $L) break;
                if (!$rep1[$L - $first]) continue;
                $parts = [$first];
                $rest  = $L - $first;
                while ($rest > 0) { $parts[] = $via[$rest]; $rest -= $via[$rest]; }
                return ['target' => $L, 'parts' => $parts];
            }
        }
        return null;
    }

    /**
     * A shortest concrete string this pattern accepts, or null when one cannot
     * be produced. Used to decide, at config time, whether a format-only
     * alternate would swallow a value a check-bearing one is meant to verify.
     *
     * Covers the pattern class this module supports: literals, escaped
     * literals, character classes (including negated ones), ".", groups,
     * alternation - the first branch is taken, which is enough, since ANY
     * member of the check-bearing pattern proves the overlap - and the
     * quantifiers ?, +, *, {n}, {n,m}. Lookaround returns null.
     *
     * The result is VERIFIED against the pattern's own compiled regex before it
     * is returned, so a witness this builder gets wrong is discarded rather
     * than used. The guard can therefore only ever fire on a string both
     * patterns provably accept, never on a guess - which is what lets the
     * builder pick ID-like members heuristically without risking a false
     * refusal.
     */
    public static function patternWitness($pattern)
    {
        $p = preg_replace('/^\\^/', '', (string) $pattern);
        $p = preg_replace('/\\$$/', '', $p);
        $i = 0;
        $out = self::witnessSeq($p, $i, 0);
        if ($out === null) return null;
        // A top-level "|" is fine - the first branch was taken. Anything else
        // left over (a stray ")") means the pattern is not balanced.
        if ($i < strlen($p) && $p[$i] !== '|') return null;
        $why = '';
        $re = self::gatePattern($pattern, $why, true);
        if ($re === null) return null;
        return self::patTest($re, $out) ? $out : null;         // verify, or no claim
    }

    /**
     * One alternative of a pattern, from $i, stopping at "|" or ")" at this
     * level. Returns null when the shape is outside the supported class.
     */
    private static function witnessSeq($p, &$i, $depth)
    {
        if ($depth > 8) return null;                            // absurd nesting
        $n = strlen($p);
        $out = '';
        while ($i < $n) {
            $c = $p[$i];
            if ($c === '|' || $c === ')') break;                // this alternative ends
            $atom = null;
            if ($c === '(') {
                $i++;
                if ($i < $n && $p[$i] === '?') {
                    // "(?:" is an ordinary group; lookaround and the rest
                    // constrain rather than contribute, so make no claim.
                    if ($i + 1 < $n && $p[$i + 1] === ':') $i += 2;
                    else return null;
                }
                $atom = self::witnessSeq($p, $i, $depth + 1);
                if ($atom === null) return null;
                if (!self::skipToGroupEnd($p, $i)) return null;
            } elseif ($c === '\\') {
                $i++;
                if ($i >= $n) return null;
                $e = $p[$i];
                if ($e === 'd') $atom = '0';
                elseif ($e === 'w') $atom = 'A';
                elseif ($e === 's') $atom = ' ';
                elseif ($e === 'D' || $e === 'W' || $e === 'S') return null;
                else $atom = $e;                                // escaped literal
                $i++;
            } elseif ($c === '[') {
                $close = self::classEnd($p, $i);
                if ($close === -1) return null;
                $body = substr($p, $i + 1, $close - $i - 1);
                $neg = ($body !== '' && $body[0] === '^');
                if ($neg) $body = substr($body, 1);
                if ($body === '') return null;
                $cls = self::expandClass($body);
                if ($cls === null) return null;
                $atom = $neg ? self::firstOutside($cls) : self::firstInside($cls);
                if ($atom === null) return null;
                $i = $close + 1;
            } elseif ($c === '.') {
                $atom = 'A';
                $i++;
            } else {
                $atom = $c;
                $i++;
            }
            $min = 1;
            if ($i < $n) {
                $q = $p[$i];
                if ($q === '?') { $min = 0; $i++; }
                elseif ($q === '+') { $min = 1; $i++; }
                elseif ($q === '*') { $min = 0; $i++; }
                elseif ($q === '{') {
                    $close = strpos($p, '}', $i + 1);
                    if ($close === false) return null;
                    $spec = substr($p, $i + 1, $close - $i - 1);
                    if (!preg_match('/^([0-9]+)(,([0-9]*))?$/', $spec, $m)) return null;
                    $min = (int) $m[1];
                    $i = $close + 1;
                }
            }
            if ($min > self::MAX_ID_LEN) return null;
            $out .= str_repeat($atom, $min);
            if (strlen($out) > self::MAX_ID_LEN) return null;
        }
        return $out;
    }

    /** Advance past the remaining alternatives of the group we are inside. */
    private static function skipToGroupEnd($p, &$i)
    {
        $n = strlen($p);
        $lvl = 1;
        while ($i < $n) {
            $ch = $p[$i];
            if ($ch === '\\') { $i += 2; continue; }
            if ($ch === '[') {
                $close = self::classEnd($p, $i);
                if ($close === -1) return false;
                $i = $close + 1;
                continue;
            }
            if ($ch === '(') $lvl++;
            elseif ($ch === ')') { $lvl--; if ($lvl === 0) { $i++; return true; } }
            $i++;
        }
        return false;
    }

    /** Index of the "]" closing the class at $i, or -1. */
    private static function classEnd($p, $i)
    {
        $n = strlen($p);
        $j = $i + 1;
        if ($j < $n && $p[$j] === '^') $j++;
        if ($j < $n && $p[$j] === ']') $j++;                    // a literal "]" first
        for (; $j < $n; $j++) {
            if ($p[$j] === '\\') { $j++; continue; }
            if ($p[$j] === ']') return $j;
        }
        return -1;
    }

    // A real ID is far likelier to be alphanumeric than to start with a space,
    // and a witness that LOOKS like an ID is the one most likely to expose an
    // overlap. Only the choice among valid members is heuristic - every witness
    // is still verified against the real regex before use, so a poor pick can
    // cost a missed warning but never a false refusal.
    const WITNESS_PREFERENCE = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-abcdefghijklmnopqrstuvwxyz';

    /** The most ID-like member of an expanded class. */
    private static function firstInside($cls)
    {
        if ($cls === '') return null;
        for ($k = 0; $k < strlen(self::WITNESS_PREFERENCE); $k++) {
            if (strpos($cls, self::WITNESS_PREFERENCE[$k]) !== false) return self::WITNESS_PREFERENCE[$k];
        }
        return $cls[0];
    }

    /** The most ID-like printable-ASCII character an expanded class excludes. */
    private static function firstOutside($cls)
    {
        for ($k = 0; $k < strlen(self::WITNESS_PREFERENCE); $k++) {
            if (strpos($cls, self::WITNESS_PREFERENCE[$k]) === false) return self::WITNESS_PREFERENCE[$k];
        }
        for ($ch = 0x20; $ch <= 0x7E; $ch++) {
            if (strpos($cls, chr($ch)) === false) return chr($ch);
        }
        return null;
    }

    /** True iff the (JS-style) pattern compiles as an anchored PCRE. */
    public static function patternCompiles($pattern)
    {
        $why = '';
        return self::gatePattern($pattern, $why, true) !== null;
    }

    /**
     * Whether $pattern uses a regex escape that only works with JavaScript's "u"
     * flag — \p{...} \P{...} \u{...} \x{...} or \k<...> — which the browser (no u
     * flag) and the server (PCRE /u) enforce DIFFERENTLY (F2, F2-BYPASS-01).
     * Escaped-backslash pairs are stripped first so a literal-backslash pattern
     * like "\\u{2}" is NOT mistaken for a real \u escape (F2-OVERREJECT-02). Keep
     * in sync with QRID_uFlagEscape (js).
     */
    public static function usesUFlagEscape($pattern)
    {
        $d = str_replace('\\\\', '', (string) $pattern);    // drop escaped-backslash pairs (parity)
        return preg_match('/\\\\[pPux]\{/', $d) === 1 || strpos($d, '\\k<') !== false;
    }

    /**
     * THE one place an ID pattern is admitted and compiled on the server.
     * Returns the anchored PCRE, or null with $why set to the designer-facing
     * sentence AnnotationRules::checkFragment reports.
     *
     * Extracted because the identical chain lived in the single-field factory,
     * the pooled factory (both js) and checkFragment — three copies that had to
     * be edited together, and a rule with SEVERAL patterns would have made it
     * five. Twin of QRID_gatePattern (js); the gates are the same four plus the
     * server-only (?P<...> and is_string checks, which the browser cannot hit.
     *
     * $compileOnly skips the parity gates for callers that only need to know
     * whether PCRE accepts the syntax (patternCompiles).
     */
    public static function gatePattern($pattern, &$why = null, $compileOnly = false)
    {
        $why = '';
        if (!$compileOnly) {
            if (!is_string($pattern)) {
                $why = 'the format pattern must be a regex string.';
                return null;
            }
            if (preg_match('/[^\x20-\x7E]/', $pattern)) {
                // The client (JS RegExp, UTF-16) and server (PCRE /u, code
                // points) are only proven to agree on printable ASCII.
                $why = 'the format pattern must contain printable ASCII only — '
                    . 'the browser and server regex engines are only guaranteed to agree on that subset.';
                return null;
            }
            if (preg_match('/\\\\[AZ]/', $pattern)) {
                $why = 'the format pattern uses Python-only \A or \Z anchors — patterns are '
                    . 'JavaScript regex; use ^ and $ instead (anchors are optional anyway).';
                return null;
            }
            if (strpos($pattern, '(?P<') !== false) {
                $why = 'the format pattern uses Python-only (?P<name>...) groups, '
                    . 'which JavaScript cannot compile.';
                return null;
            }
            if (self::usesUFlagEscape($pattern)) {
                // \p{}, \P{}, \u{}, \x{} and \k<> only work with JavaScript's "u"
                // flag; the browser compiles ID patterns WITHOUT it (so \p reads as
                // a literal "p" and \x{41} as x{41}) while the server matches with
                // PCRE /u, so the two engines would disagree on a valid value (F2 +
                // F2-BYPASS-01). Reject at config time like \A/\Z and (?P<...),
                // keeping the proven-parity subset to explicit classes.
                $why = 'the format pattern uses a Unicode-property, code-point or named escape '
                    . '(\p{...}, \P{...}, \u{...}, \x{...} or \k<...>) that only works with '
                    . 'JavaScript\'s "u" flag — the browser compiles ID patterns without it, so the '
                    . 'value would validate differently in the browser and on the server. Use explicit '
                    . 'character classes such as [A-Z] or [0-9] instead.';
                return null;
            }
            if (self::riskyPattern($pattern)) {
                $why = 'the format pattern looks catastrophically backtracking (nested '
                    . 'quantifiers, a repeated ambiguous group, overlapping unbounded quantifiers, or a '
                    . 'long run of overlapping bounded quantifiers — e.g. (a+)+, (a|aa)+, .*.* / '
                    . '[0-9]*[0-9]*, or A{1,20}A{1,20}A{1,20}A{1,20}A{1,20}) — rewrite it so no ambiguous '
                    . 'group repeats, no two unbounded quantifiers overlap, and no long run of bounded '
                    . 'quantifiers shares a character class (use a disjoint class or a fixed length).';
                return null;
            }
        }
        $body = preg_replace('/^\^/', '', (string) $pattern);
        $body = preg_replace('/\$$/', '', $body);
        $re = self::compilePattern($body);
        if ($re === null) {
            $why = 'the format pattern does not compile as a regex — check the syntax.';
            return null;
        }
        return $re;
    }

    /** Build an anchored PCRE from a JS-style regex body, or null if uncompilable. */
    private static function compilePattern($body)
    {
        $delims = ['/', '#', '~', '!', '@', '%', ';', ':', '|', '='];
        $d = null;
        foreach ($delims as $cand) {
            if (strpos($body, $cand) === false) { $d = $cand; break; }
        }
        if ($d === null) { $d = '/'; $body = str_replace('/', '\\/', $body); }
        $re = $d . '^(?:' . $body . ')$' . $d . 'u';
        return (@preg_match($re, '') === false) ? null : $re;
    }

    /**
     * True iff $t matches the compiled pattern. On a PCRE ENGINE failure
     * (backtrack/recursion limit — possible for a catastrophic pattern the
     * heuristic missed) it flags the run so the whole pooled field bails to
     * "unconfigurable" instead of silently dropping the window into a false
     * junk / invalid-ID verdict. Mirrors the preg_last_error guard in
     * matchesPattern() for the single-field path.
     */
    // Public because checkFragment's config-time overlap check needs the same
    // PCRE-error-guarded match the parser uses; a bare preg_match there could
    // report an engine failure as a real match.
    public static function patTest($re, $t)
    {
        $m = @preg_match($re, $t);
        if ($m === false || preg_last_error() !== PREG_NO_ERROR) {
            self::$pooledPcreError = true;
            return false;
        }
        return $m === 1;
    }

    /**
     * Server-side single-field validation mirroring the client's rule order:
     * format (idPattern) first, then check character. Returns ['ok', 'reason'].
     */
    public static function validateSingleField(array $cfg, $value)
    {
        $ALTS = self::alternatesOf($cfg);
        if ($ALTS === null) return ['ok' => true, 'reason' => 'unconfigurable'];
        // COR-004 lives HERE, not inside matchesPattern. Outside printable ASCII
        // the browser (UTF-16) and PCRE /u disagree, so the server fails OPEN
        // rather than log a mismatch the client never showed. Left in
        // matchesPattern, that fail-open "true" would read as "alternate 1's
        // pattern matched" and the alternate's CHECK would then run on the value
        // and fail - converting a deliberate fail-open into a false finding.
        $norm = trim(self::normalize($value, '', true, true, null));
        if (preg_match('/[^ -~]/', $norm)) return ['ok' => true, 'reason' => 'valid'];

        // An algorithm this engine does not implement is a CONFIGURATION problem,
        // not a data problem: compute() would throw inside validateId and read
        // back as a failed check, filing a false finding against a good ID.
        // pooledState has refused it since the rewrite; this is its twin, and
        // the rule-level gate at UniversalValidator::ruleFindings has no
        // alternate-level equivalent (COR-002).
        foreach ($ALTS as $A) {
            if (!self::knownAlgorithm($A['algorithm'])) {
                return ['ok' => true, 'reason' => 'unconfigurable'];
            }
        }
        $anyPattern = false; $shapeMatched = false;
        foreach ($ALTS as $A) {
            $pattern = ($A['pattern'] !== null && $A['pattern'] !== '') ? $A['pattern'] : null;
            if ($pattern !== null) {
                $anyPattern = true;
                if (!self::matchesPattern($value, $pattern)) continue;
            }
            $shapeMatched = true;
            if ($A['algorithm'] === 'none') {
                // format-only: the shape IS the whole test
                return ['ok' => true, 'reason' => $pattern !== null ? 'valid' : 'no-op'];
            }
            if (self::validateId($A['algorithm'], $A['source'], $A['strip'], $value)) {
                return ['ok' => true, 'reason' => 'valid'];
            }
        }
        // Reason precedence, byte-identical to the old two-branch order for a
        // single-format rule: a SHAPE that matched but whose check failed is a
        // check-character error; nothing matching any shape is a format error.
        if ($shapeMatched) return ['ok' => false, 'reason' => 'check-character'];
        if ($anyPattern)   return ['ok' => false, 'reason' => 'format'];
        return ['ok' => false, 'reason' => 'check-character'];
    }

    // -- server-side pooled parser (faithful port of QRIDPooledInit) ---------
    //
    // Behavior is frozen against tests/pooled_fixture.json, recomputed by BOTH
    // runtimes in CI, so the server parser can never drift from the browser one.

    /** Set true when a PCRE engine failure occurs during a pooled parse, so the
     *  whole field bails to "unconfigurable" rather than emitting a false verdict. */
    private static $pooledPcreError = false;

    private static function isPosInt($x)
    {
        if (is_int($x)) return $x > 0;
        if (is_string($x)) return ctype_digit($x) && (int) $x > 0;
        return is_numeric($x) && $x > 0 && floor($x) == $x;
    }

    /** Resolve LENS / KEEP / regex from a pooled rule config, or null if unsafe. */
    private static function pooledState(array $cfg)
    {
        $ALPHA  = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
        $hasAlts = (isset($cfg['alternates']) && $cfg['alternates'] !== null && $cfg['alternates'] !== '');

        // One rule = one or more ALTERNATES. A legacy scalar rule normalizes to
        // exactly one, so everything below is a single loop rather than two
        // code paths. Twin of the js pooled makeVariant.
        $ALTS = self::alternatesOf($cfg);
        if ($ALTS === null) return null;
        // Two sources of truth for one fact: with alternates, lengths live on
        // the alternates and the rule-level keys must be absent.
        if ($hasAlts && (isset($cfg['idPattern']) && $cfg['idPattern'] !== '')) return null;
        if ($hasAlts && ((isset($cfg['idLengths']) && $cfg['idLengths'] !== null)
                || (isset($cfg['idMinLen']) && $cfg['idMinLen'] !== null && $cfg['idMinLen'] !== '')
                || (isset($cfg['idMaxLen']) && $cfg['idMaxLen'] !== null && $cfg['idMaxLen'] !== ''))) return null;

        $checkMode = false; $regexOnly = true;
        foreach ($ALTS as $i => $A) {
            $chk = ($A['algorithm'] !== 'none');
            if ($chk && !self::knownAlgorithm($A['algorithm'])) return null;
            if ($chk && $A['source'] !== 'normalized_id' && $A['source'] !== 'digits_only'
                     && $A['source'] !== 'sequence_only') return null;
            $pat = ($A['pattern'] !== null && $A['pattern'] !== '') ? $A['pattern'] : null;
            if (!$chk && $pat === null) return null;                 // nothing to validate
            $re = null;
            if ($pat !== null) {
                if (self::riskyPattern($pat)) return null;            // catastrophic -> unconfigurable
                $body = preg_replace('/^\^/', '', (string) $pat);
                $body = preg_replace('/\$$/', '', $body);
                $re = self::compilePattern($body);
                if ($re === null) return null;                       // cannot segment safely
            }
            $ALTS[$i]['check']     = $chk;
            $ALTS[$i]['re']        = $re;
            $ALTS[$i]['regexOnly'] = (!$chk && $re !== null);
            $ALTS[$i]['nCheck']    = $chk ? self::nCheckChars($A['algorithm']) : 0;
            if ($chk) { $checkMode = true; $regexOnly = false; }
            if ($hasAlts && $ALTS[$i]['lengths'] === null) return null;  // pooled needs a length per format
        }

        $LENS = [];
        $minLen = (isset($cfg['idMinLen']) && $cfg['idMinLen'] !== null && $cfg['idMinLen'] !== '') ? (int) $cfg['idMinLen'] : 8;
        $maxLen = (isset($cfg['idMaxLen']) && $cfg['idMaxLen'] !== null && $cfg['idMaxLen'] !== '') ? (int) $cfg['idMaxLen'] : 14;
        if ($hasAlts) {
            // The safety proofs are properties of the WHOLE length universe, not
            // of one alternate: [9] and [5,4] are individually safe and jointly
            // unsafe, because 9 = 5 + 4.
            foreach ($ALTS as $A) foreach ($A['lengths'] as $L) $LENS[] = $L;
            $LENS = array_values(array_unique($LENS));
            sort($LENS);
            $minLen = $LENS[0];
            $maxLen = $LENS[count($LENS) - 1];
            if ($maxLen > self::MAX_ID_LEN) return null;
            if (self::swallowSum($LENS) !== null) return null;       // union sum-swallow
        } elseif (isset($cfg['idLengths']) && $cfg['idLengths'] !== null) {
            $lens = $cfg['idLengths'];
            if (!is_array($lens) || !count($lens)) return null;
            foreach ($lens as $L) if (!self::isPosInt($L)) return null;
            $lens = array_values(array_unique(array_map('intval', $lens)));
            sort($lens);
            if (self::swallowSum($lens) !== null) return null; // sum-swallow (2+ terms)
            $LENS = $lens;
            $minLen = $lens[0];
            $maxLen = $lens[count($lens) - 1];
        } else {
            if (!self::isPosInt($minLen) || !self::isPosInt($maxLen)) return null;
            if ($maxLen < $minLen) return null;
            if ($maxLen >= 2 * $minLen) return null;
            if ($maxLen > self::MAX_ID_LEN) return null; // BEFORE the range loop: no huge allocation
            $minLen = max($minLen, $ALTS[0]['nCheck'] + 1);
            for ($L = $minLen; $L <= $maxLen; $L++) $LENS[] = $L;
        }
        // Every alternate that did not declare its own lengths inherits the
        // rule-level set - which is exactly the legacy single-alternate case,
        // so PAIRS below is byte-for-byte today's LENS.
        foreach ($ALTS as $i => $A) if ($ALTS[$i]['lengths'] === null) $ALTS[$i]['lengths'] = $LENS;
        // Bucketed, NOT sorted: length ascending on the outside keeps the DP's
        // early break valid and preserves "shortest member wins ties";
        // declaration order on the inside gives precedence. A comparator would
        // order ties differently on PHP 7.4, where usort is not stable, and the
        // two runtimes would silently disagree.
        $PAIRS = []; $RESCAN = [];
        foreach ($LENS as $L) {
            foreach ($ALTS as $ai => $A) {
                if (!in_array($L, $A['lengths'], true)) continue;
                $P = ['len' => $L, 'alt' => $ai, 're' => $A['re'], 'regexOnly' => $A['regexOnly'],
                      'algo' => $A['algorithm'], 'source' => $A['source'], 'strip' => $A['strip']];
                $PAIRS[] = $P;
                // Regex-only alternates never take part in the junk re-scan: the
                // shape IS their test, so stamping valid=false on a shape match
                // would report a check-character error against an ID that has no
                // check character.
                if (!$A['regexOnly'] && $A['re'] !== null) $RESCAN[] = $P;
            }
        }
        // Hard work bounds: parsing tests every candidate (alternate, length)
        // pair at every position, so unbounded lengths turn one keystroke/save
        // into seconds of regex + check-character work (PER-002). Beyond the
        // caps the rule is unconfigurable (and rejected at settings-save time
        // upstream). For a single-format rule |PAIRS| IS |LENS|.
        if (!count($PAIRS)) return null;
        if ($maxLen > self::MAX_ID_LEN || count($PAIRS) > self::MAX_LEN_CHOICES) return null;

        $keepCfg = isset($cfg['keepChars']) ? (string) $cfg['keepChars'] : '';
        // Non-ASCII keep characters would make the byte-indexed splitter below
        // disagree with the browser's UTF-16 one; the audited subset is ASCII.
        if (strlen($keepCfg) > self::MAX_KEEP_CHARS || preg_match('/[^\x20-\x7E]/', $keepCfg)) return null;

        // clean() runs ONCE over the whole pooled string, before anything is
        // split, so there is one KEEP set for the field: the union over the
        // alternates. That union is also a hazard - an algorithm that can emit
        // "*" makes "*" survive for a sibling alternate that cannot contain it,
        // changing the string recorded for that sibling. checkFragment refuses a
        // rule whose alternates disagree about KEEP unless the designer declares
        // the union in keepChars.
        $KEEP = $ALPHA . $keepCfg;
        foreach ($ALTS as $A) {
            $Ki = self::pooledKeepFor($A, $ALPHA . $keepCfg);
            for ($i = 0; $i < strlen($Ki); $i++) {
                if (strpos($KEEP, $Ki[$i]) === false) $KEEP .= $Ki[$i];
            }
        }

        return [
            'checkMode' => $checkMode, 'regexOnly' => $regexOnly,
            'minLen' => $minLen, 'maxLen' => $maxLen, 'LENS' => $LENS, 'KEEP' => $KEEP,
            'ALTS' => $ALTS, 'PAIRS' => $PAIRS, 'RESCAN' => $RESCAN,
        ];
    }

    /** The characters ONE alternate needs to survive cleaning. Twin of keepFor (js). */
    private static function pooledKeepFor(array $A, $base)
    {
        $K = $base;
        if ($A['check']) {
            $CA = self::checkAlphabet($A['algorithm']);
            for ($i = 0; $i < strlen($CA); $i++) {
                if (strpos($K, $CA[$i]) === false) $K .= $CA[$i];
            }
        }
        if ($A['re'] !== null) {
            $pat = (string) $A['pattern']; $meta = '\\^$.|?*+()[]{}';
            for ($i = 0; $i < strlen($pat); $i++) {
                $pc = $pat[$i];
                if ($pc === '\\') {
                    $i++;
                    if ($i < strlen($pat)) {
                        $pc = $pat[$i];
                        if (strpos($meta, $pc) !== false && strpos($K, $pc) === false) $K .= $pc;
                    }
                    continue;
                }
                if (strpos($meta, $pc) === false && !preg_match('/[A-Za-z0-9]/', $pc) && strpos($K, $pc) === false) {
                    $K .= $pc;
                }
            }
        }
        return $K;
    }

    /** Does THIS (alternate, length) pair accept the token? Twin of verifiesAs (js). */
    private static function pooledVerifiesAs(array $P, $t)
    {
        if ($P['re'] !== null && !self::patTest($P['re'], $t)) return false;
        if ($P['regexOnly']) return true;
        return self::validateId($P['algo'], $P['source'], $P['strip'], $t);
    }

    /**
     * Which alternate claims this token? First in declaration order, computed
     * AFTER segmentation for reporting only - never an input to the DP score.
     * Twin of claimedBy (js).
     */
    public static function pooledClaimedBy(array $st, $t)
    {
        foreach ($st['ALTS'] as $i => $A) {
            if ($A['re'] !== null && !self::patTest($A['re'], $t)) continue;
            if ($A['regexOnly'] || self::validateId($A['algorithm'], $A['source'], $A['strip'], $t)) return $i;
        }
        return -1;
    }

    private static function pooledBetter(array $a, array $b)
    {
        if ($a['tok'] !== $b['tok']) return $a['tok'] > $b['tok'];
        if ($a['runs'] !== $b['runs']) return $a['runs'] < $b['runs'];
        if ($a['maxL'] !== $b['maxL']) return $a['maxL'] < $b['maxL'];
        return $a['chars'] > $b['chars'];
    }

    private static function pooledSegments(array $st, $raw)
    {
        $s = self::normalize($raw, '', true, true, $st['KEEP']); // clean(): keep only KEEP chars
        $N = strlen($s);
        $sc = array_fill(0, $N + 1, null);
        $sc[$N] = ['tok' => 0, 'maxL' => 0, 'runs' => 0, 'chars' => 0, 'startsJunk' => false,
                   'move' => -1, 'alt' => -1];
        for ($i = $N - 1; $i >= 0; $i--) {
            $c = $sc[$i + 1];
            $best = [
                'tok' => $c['tok'], 'maxL' => $c['maxL'],
                'runs' => $c['runs'] + ($c['startsJunk'] ? 0 : 1),
                'chars' => $c['chars'] + 1, 'startsJunk' => true, 'move' => 0, 'alt' => -1,
            ];
            foreach ($st['PAIRS'] as $P) {          // length-ascending: shortest member wins ties
                $L = $P['len'];
                if ($L > $N - $i) break;
                if (!self::pooledVerifiesAs($P, substr($s, $i, $L))) continue;
                $ch = $sc[$i + $L];
                $cand = [
                    'tok' => $ch['tok'] + 1, 'maxL' => ($L > $ch['maxL'] ? $L : $ch['maxL']),
                    'runs' => $ch['runs'], 'chars' => $ch['chars'], 'startsJunk' => false, 'move' => $L,
                    'alt' => $P['alt'],
                ];
                if (self::pooledBetter($cand, $best)) $best = $cand;
            }
            $sc[$i] = $best;
        }
        $segs = []; $pos = 0; $junk = '';
        while ($pos < $N) {
            $m = $sc[$pos]['move'];
            if ($m > 0) {
                if ($junk !== '') { $segs[] = ['type' => 'junk', 'text' => $junk]; $junk = ''; }
                // WHICH alternate won is already known here - carry it rather
                // than re-deriving it later, which could credit a different,
                // more permissive alternate than the one actually verified
                // through. Still not an input to pooledBetter. Twin of the js.
                $segs[] = ['type' => 'id', 'id' => substr($s, $pos, $m), 'valid' => true,
                           'alt' => isset($sc[$pos]['alt']) ? $sc[$pos]['alt'] : -1];
                $pos += $m;
            } else {
                $junk .= $s[$pos]; $pos++;
            }
        }
        if ($junk !== '') $segs[] = ['type' => 'junk', 'text' => $junk];

        // re-scan junk for well-formed-but-wrong-check members (check + pattern only)
        if (count($st['RESCAN'])) {
            $out = [];
            foreach ($segs as $seg) {
                if ($seg['type'] !== 'junk') { $out[] = $seg; continue; }
                $rest = $seg['text']; $buf = '';
                while (strlen($rest)) {
                    $hit = '';
                    // Only lengths the rule actually DECLARES. This walked the
                    // contiguous range minLen..maxLen, so idLengths [10,12]
                    // tested length 11 and could stamp an "invalid ID" chip the
                    // segmentation pass can never produce. Twin of the js loop.
                    $hitAlt = -1;
                    foreach ($st['RESCAN'] as $R) {
                        $L2 = $R['len'];
                        if ($L2 > strlen($rest)) break;             // length-ascending
                        if (self::patTest($R['re'], substr($rest, 0, $L2))) {
                            $hit = substr($rest, 0, $L2); $hitAlt = $R['alt']; break;
                        }
                    }
                    if ($hit !== '') {
                        if ($buf !== '') { $out[] = ['type' => 'junk', 'text' => $buf]; $buf = ''; }
                        $out[] = ['type' => 'id', 'id' => $hit, 'valid' => false, 'alt' => $hitAlt];
                        $rest = substr($rest, strlen($hit));
                    } else {
                        $buf .= $rest[0]; $rest = substr($rest, 1);
                    }
                }
                if ($buf !== '') $out[] = ['type' => 'junk', 'text' => $buf];
            }
            $segs = $out;
        }
        return $segs;
    }

    /**
     * Segment a pooled field into members + junk. Returns a list of
     *   ['type'=>'id','id'=>..,'valid'=>bool]  or  ['type'=>'junk','text'=>..]
     * or null when the config is unsafe (client shows a config error instead).
     */
    /** Per-rule scan cap — the PHP twin of the client's SCAN_CAP formula. */
    public static function pooledScanCap(array $st)
    {
        $lens = count($st['PAIRS']) ?: 1;   // for a single-format rule this IS |LENS|
        $max  = $st['maxLen'] ?: 1;
        $cap  = (int) floor(self::POOLED_WORK_BUDGET / ($lens * $max));
        if ($cap < 256) $cap = 256;
        return min(self::MAX_POOLED_LEN, $cap);
    }

    public static function pooledParse(array $cfg, $raw)
    {
        $st = self::pooledState($cfg);
        if ($st === null) return null;
        // Over-budget input: no verdict at all, never a slow parse — the client
        // bails identically at the same cap, so the runtimes cannot disagree.
        if (mb_strlen((string) $raw, 'UTF-8') > self::pooledScanCap($st)) return null;
        self::$pooledPcreError = false;
        $segs = self::pooledSegments($st, (string) $raw);
        // A PCRE engine failure during segmentation makes the result untrustworthy;
        // treat the field as unconfigurable (no verdict) rather than log a false one.
        return self::$pooledPcreError ? null : $segs;
    }

    /** Server-side pooled verdict mirroring the browser render() problem checks. */
    public static function validatePooledField(array $cfg, $raw)
    {
        $segs = self::pooledParse($cfg, $raw);
        if ($segs === null) return ['ok' => true, 'reason' => 'unconfigurable', 'count' => 0];
        $ids = 0; $junk = 0; $bad = 0; $dups = 0; $seen = [];
        foreach ($segs as $seg) {
            if ($seg['type'] === 'id') {
                $ids++;
                if (!$seg['valid']) $bad++;
                if (isset($seen[$seg['id']])) $dups++;
                $seen[$seg['id']] = true;
            } else {
                $junk++;
            }
        }
        $problems = [];
        if (!$ids) $problems[] = 'no-id';
        if ($bad)  $problems[] = 'check-character';
        if ($junk) $problems[] = 'junk';
        if ($dups) $problems[] = 'duplicate';
        $expected = (isset($cfg['expectedIds']) && $cfg['expectedIds']) ? (int) $cfg['expectedIds'] : null;
        if ($expected && $ids !== $expected) $problems[] = 'count';
        return ['ok' => count($problems) === 0, 'reason' => implode(';', $problems), 'count' => $ids];
    }

    // -- engines ------------------------------------------------------------

    private static function idx($alphabet, $ch)
    {
        $i = strpos($alphabet, $ch);
        if ($i === false) {
            throw new \InvalidArgumentException("character '$ch' not in alphabet");
        }
        return $i;
    }

    /** ISO/IEC 7064 pure systems: p = ((p + d) * r) mod M. */
    private static function pure($payload, $alphabet, $M, $r, $n, $checkAlphabet)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $p = 0;
        foreach (str_split($payload) as $ch) {
            $d = self::idx($alphabet, $ch);
            $p = (($p + $d) * $r) % $M;
        }
        for ($k = 0; $k < $n - 1; $k++) {
            $p = ($p * $r) % $M;
        }
        if ($n === 1) {
            $cv = ((1 - $p) % $M + $M) % $M;
            return $checkAlphabet[$cv];
        }
        // Multi-char (Mod 97-10): check value in [2, M+1], NOT reduced mod M;
        // emit n radix-r digits, high digit first, via the payload alphabet.
        $cv = ($M + 1) - $p;
        $digits = [];
        $x = $cv;
        for ($k = 0; $k < $n; $k++) {
            $digits[] = $alphabet[$x % $r];
            $x = intdiv($x, $r);
        }
        return implode('', array_reverse($digits));
    }

    /** ISO/IEC 7064 hybrid systems (Mod n+1,n over the alphabet). */
    private static function hybrid($payload, $alphabet)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $modulus = strlen($alphabet);
        $check = intdiv($modulus, 2);
        foreach (str_split($payload) as $ch) {
            $d = self::idx($alphabet, $ch);
            $check = ((($check ?: $modulus) * 2) % ($modulus + 1) + $d) % $modulus;
        }
        $v = ((1 - (($check ?: $modulus) * 2) % ($modulus + 1)) % $modulus + $modulus) % $modulus;
        return $alphabet[$v];
    }

    /** Hybrid recurrence over pre-mapped values -> check value in [0, modulus). */
    private static function hybridValue($values, $modulus)
    {
        $check = intdiv($modulus, 2);
        foreach ($values as $d) {
            $check = ((($check ?: $modulus) * 2) % ($modulus + 1) + $d) % $modulus;
        }
        return ((1 - (($check ?: $modulus) * 2) % ($modulus + 1)) % $modulus + $modulus) % $modulus;
    }

    /** Letters-only variant 1: fold 36 symbols onto 26 letters, one letter out. */
    private static function letters1($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $vals = [];
        foreach (str_split($payload) as $ch) {
            $vals[] = self::idx(self::ALNUM36, $ch) % 26;
        }
        $v = self::hybridValue($vals, 26);
        $A = self::LETTERS26;
        return $A[$v];
    }

    /** Letters-only variant 2: full Mod 37,36 value as two base-6 letters (A-F). */
    private static function letters2($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $vals = [];
        foreach (str_split($payload) as $ch) {
            $vals[] = self::idx(self::ALNUM36, $ch);
        }
        $v = self::hybridValue($vals, 36);
        $L = 'ABCDEF';
        return $L[intdiv($v, 6)] . $L[$v % 6];
    }

    private static function damm($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        static $T = [
            [0, 3, 1, 7, 5, 9, 8, 6, 4, 2],
            [7, 0, 9, 2, 1, 5, 4, 8, 6, 3],
            [4, 2, 0, 6, 8, 7, 1, 3, 5, 9],
            [1, 7, 5, 0, 9, 8, 3, 4, 2, 6],
            [6, 1, 2, 3, 0, 4, 5, 9, 7, 8],
            [3, 6, 7, 4, 2, 0, 9, 5, 8, 1],
            [5, 8, 6, 9, 7, 2, 0, 1, 3, 4],
            [8, 9, 4, 5, 3, 6, 2, 0, 1, 7],
            [9, 4, 3, 8, 6, 1, 7, 2, 0, 5],
            [2, 5, 8, 1, 4, 3, 6, 7, 9, 0],
        ];
        $interim = 0;
        foreach (str_split($payload) as $ch) {
            $d = self::idx(self::DIGITS, $ch);
            $interim = $T[$interim][$d];
        }
        return (string) $interim;
    }

    private static function verhoeff($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $D = self::verhoeffD();
        $P = self::powerPerm();
        $INV = [0, 4, 3, 2, 1, 5, 6, 7, 8, 9];
        $c = 0;
        foreach (array_reverse(str_split($payload)) as $i => $ch) {
            $d = self::idx(self::DIGITS, $ch);
            $c = $D[$c][$P[($i + 1) % 8][$d]];
        }
        return (string) $INV[$c];
    }

    private static function luhn($payload)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $total = 0;
        foreach (array_reverse(str_split($payload)) as $idx => $ch) {
            $d = self::idx(self::DIGITS, $ch);
            if ($idx % 2 === 0) {
                $d *= 2;
                if ($d > 9) $d -= 9;
            }
            $total += $d;
        }
        return (string) ((10 - ($total % 10)) % 10);
    }

    /**
     * Generic positional weighted-sum modulus check (mirror WeightedModulus in
     * check_characters.py and weightedModulus in js/engine.js). Weights each
     * digit by position, sums, reduces mod M, and maps to the check alphabet.
     * Covers gs1_mod10, aba_mod10, mrz_mod10 and weighted_mod11 from the
     * WEIGHTED_SCHEMES table. Digit payload only.
     */
    private static function weighted($payload, array $spec)
    {
        if ($payload === '') throw new \InvalidArgumentException('payload must be non-empty');
        $M = $spec['modulus'];
        $cycle = ($spec['mode'] === 'cycle');
        $weights = $cycle ? $spec['weights'] : null;
        $wlen = $cycle ? count($weights) : 0;
        $fromRight = ($spec['from'] === 'right');
        $chars = str_split($payload);
        $n = count($chars);
        $total = 0;
        for ($i = 0; $i < $n; $i++) {
            $d = self::idx(self::DIGITS, $chars[$i]);
            $pos = $fromRight ? ($n - 1 - $i) : $i;
            $w = $cycle ? $weights[$pos % $wlen] : ($spec['start'] + $spec['step'] * $pos);
            $total += $d * $w;
        }
        $v = $spec['complement'] ? (($M - $total % $M) % $M) : ($total % $M);
        return $spec['checkAlphabet'][$v];
    }

    /** Verhoeff D5 multiplication table. */
    private static function verhoeffD()
    {
        return [
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
            [1, 2, 3, 4, 0, 6, 7, 8, 9, 5],
            [2, 3, 4, 0, 1, 7, 8, 9, 5, 6],
            [3, 4, 0, 1, 2, 8, 9, 5, 6, 7],
            [4, 0, 1, 2, 3, 9, 5, 6, 7, 8],
            [5, 9, 8, 7, 6, 0, 4, 3, 2, 1],
            [6, 5, 9, 8, 7, 1, 0, 4, 3, 2],
            [7, 6, 5, 9, 8, 2, 1, 0, 4, 3],
            [8, 7, 6, 5, 9, 3, 2, 1, 0, 4],
            [9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
        ];
    }

    /** Verhoeff permutation family as successive powers of the base permutation. */
    private static function powerPerm()
    {
        $base = [1, 5, 7, 6, 2, 8, 3, 0, 9, 4];
        $table = [range(0, 9)];
        for ($k = 1; $k < 8; $k++) {
            $prev = $table[$k - 1];
            $row = [];
            for ($x = 0; $x < 10; $x++) {
                $row[] = $base[$prev[$x]];
            }
            $table[] = $row;
        }
        return $table;
    }
}
